import { MealPlan, Task, Autoflow } from '@/lib/types'

export const DEMO_COACH = {
  id: 'demo-coach-1',
  email: 'demo@propelcoaches.com',
  name: 'Demo Coach',
}

export const DEMO_CLIENTS = [
  {
    id: 'demo-client-1',
    role: 'client' as const,
    name: 'Liam Carter',
    email: 'liam.carter@example.com',
    phone: '+61 412 345 678',
    avatar_url: null,
    coach_id: 'demo-coach-1',
    date_of_birth: '1992-03-14',
    gender: 'Male',
    height_cm: 182,
    starting_weight_kg: 95.5,
    current_weight_kg: 88.2,
    target_weight_kg: 82.0,
    goal: 'Lose body fat and build lean muscle',
    goal_timeline: '6 months',
    dietary_preferences: ['High protein', 'No dairy'],
    training_days_per_week: 4,
    training_history: 'Trained on and off for 5 years. Comfortable with barbell movements.',
    injuries: 'Minor lower back tightness — avoid heavy deadlifts for now.',
    onboarding_completed: true,
    business_name: null,
    bio: null,
    specialisations: null,
    created_at: '2025-09-15T08:00:00Z',
    updated_at: '2026-02-20T10:00:00Z',
  },
  {
    id: 'demo-client-2',
    role: 'client' as const,
    name: 'Sophie Nguyen',
    email: 'sophie.nguyen@example.com',
    phone: '+61 423 456 789',
    avatar_url: null,
    coach_id: 'demo-coach-1',
    date_of_birth: '1996-07-22',
    gender: 'Female',
    height_cm: 163,
    starting_weight_kg: 68.0,
    current_weight_kg: 64.5,
    target_weight_kg: 60.0,
    goal: 'Tone up and improve fitness for a half marathon',
    goal_timeline: '4 months',
    dietary_preferences: ['Vegetarian', 'Gluten-free'],
    training_days_per_week: 5,
    training_history: 'Regular runner. New to structured strength training.',
    injuries: null,
    onboarding_completed: true,
    business_name: null,
    bio: null,
    specialisations: null,
    created_at: '2025-10-03T09:30:00Z',
    updated_at: '2026-02-22T11:00:00Z',
  },
  {
    id: 'demo-client-3',
    role: 'client' as const,
    name: 'Jake Wilson',
    email: 'jake.wilson@example.com',
    phone: '+61 435 567 890',
    avatar_url: null,
    coach_id: 'demo-coach-1',
    date_of_birth: '1988-11-05',
    gender: 'Male',
    height_cm: 178,
    starting_weight_kg: 78.0,
    current_weight_kg: 81.5,
    target_weight_kg: 85.0,
    goal: 'Build muscle and increase strength (bulk)',
    goal_timeline: '5 months',
    dietary_preferences: ['High calorie', 'Meal prep friendly'],
    training_days_per_week: 4,
    training_history: '3 years of consistent training. Familiar with powerlifting basics.',
    injuries: 'Previous left shoulder impingement — fully healed.',
    onboarding_completed: true,
    business_name: null,
    bio: null,
    specialisations: null,
    created_at: '2025-11-18T07:45:00Z',
    updated_at: '2026-02-25T09:00:00Z',
  },
  {
    id: 'demo-client-4',
    role: 'client' as const,
    name: 'Emma Thompson',
    email: 'emma.thompson@example.com',
    phone: '+61 447 678 901',
    avatar_url: null,
    coach_id: 'demo-coach-1',
    date_of_birth: '2000-01-30',
    gender: 'Female',
    height_cm: 168,
    starting_weight_kg: 72.5,
    current_weight_kg: 69.0,
    target_weight_kg: 65.0,
    goal: 'General health, improve energy levels and build habits',
    goal_timeline: '3 months',
    dietary_preferences: ['Balanced', 'Minimal sugar'],
    training_days_per_week: 3,
    training_history: 'Beginner — minimal gym experience. Very motivated.',
    injuries: null,
    onboarding_completed: true,
    business_name: null,
    bio: null,
    specialisations: null,
    created_at: '2025-12-01T10:00:00Z',
    updated_at: '2026-03-01T08:00:00Z',
  },
]

export const DEMO_CHECK_INS = [
  // Liam Carter
  {
    id: 'demo-ci-1',
    client_id: 'demo-client-1',
    date: '2026-03-03',
    energy: 7,
    stress: 5,
    sleep_quality: 7,
    training_difficulty: 8,
    digestion: null,
    bodyweight_kg: 88.2,
    wins: 'Hit a new squat PB — 120kg for 5 reps. Meal prep was on point all week.',
    struggles: 'Work stress made it hard to sleep on Wednesday and Thursday.',
    coach_comment: 'Brilliant week Liam — that squat PB is huge progress. Keep managing the stress as best you can.',
    loom_url: 'https://www.loom.com/share/abc123def456',
    submitted: true,
    created_at: '2026-03-03T07:00:00Z',
    photo_front_url: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=300&h=400&fit=crop&q=80',
    photo_side_url: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=300&h=400&fit=crop&q=80',
    photo_back_url: null,
  },
  {
    id: 'demo-ci-2',
    client_id: 'demo-client-1',
    date: '2026-02-24',
    energy: 6,
    stress: 6,
    sleep_quality: 6,
    training_difficulty: 7,
    digestion: null,
    bodyweight_kg: 89.1,
    wins: 'Stuck to nutrition targets 6 out of 7 days.',
    struggles: 'Missed one training session due to work commitments.',
    coach_comment: 'Solid week overall. One missed session is nothing to stress about — consistency over perfection.',
    loom_url: null,
    submitted: true,
    created_at: '2026-02-24T07:00:00Z',
    photo_front_url: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=300&h=400&fit=crop&q=80',
    photo_side_url: null,
    photo_back_url: null,
  },
  {
    id: 'demo-ci-3',
    client_id: 'demo-client-1',
    date: '2026-02-17',
    energy: 8,
    stress: 4,
    sleep_quality: 8,
    training_difficulty: 7,
    digestion: null,
    bodyweight_kg: 89.8,
    wins: 'Energy was high all week. Great session on Thursday.',
    struggles: 'Craving sweets at night — managed to stay disciplined though.',
    coach_comment: 'Love seeing the high energy scores. Your sleep and recovery are clearly paying dividends.',
    loom_url: null,
    submitted: true,
    created_at: '2026-02-17T07:00:00Z',
    photo_front_url: null,
    photo_side_url: null,
    photo_back_url: null,
  },
  // Sophie Nguyen
  {
    id: 'demo-ci-4',
    client_id: 'demo-client-2',
    date: '2026-03-04',
    energy: 8,
    stress: 3,
    sleep_quality: 9,
    training_difficulty: 6,
    digestion: null,
    bodyweight_kg: 64.5,
    wins: 'Completed a 15km long run — new distance PB. Strength sessions felt easier than ever.',
    struggles: 'Gluten-free eating on the go is still challenging when travelling.',
    coach_comment: 'Amazing run Sophie! That distance milestone is a huge deal. We\'ll keep building on this.',
    loom_url: null,
    submitted: true,
    created_at: '2026-03-04T08:00:00Z',
    photo_front_url: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=300&h=400&fit=crop&q=80',
    photo_side_url: null,
    photo_back_url: null,
  },
  {
    id: 'demo-ci-5',
    client_id: 'demo-client-2',
    date: '2026-02-25',
    energy: 7,
    stress: 4,
    sleep_quality: 8,
    training_difficulty: 6,
    digestion: null,
    bodyweight_kg: 65.0,
    wins: 'Ran 3x this week plus 2 strength sessions — all completed.',
    struggles: 'Legs were sore heading into Thursday\'s run.',
    coach_comment: 'Brilliant consistency! The soreness is normal — make sure you\'re hitting the protein targets to support recovery.',
    loom_url: null,
    submitted: true,
    created_at: '2026-02-25T08:00:00Z',
    photo_front_url: null,
    photo_side_url: null,
    photo_back_url: null,
  },
  {
    id: 'demo-ci-6',
    client_id: 'demo-client-2',
    date: '2026-02-18',
    energy: 6,
    stress: 5,
    sleep_quality: 7,
    training_difficulty: 7,
    digestion: null,
    bodyweight_kg: 65.4,
    wins: 'First time doing Bulgarian split squats — got through them!',
    struggles: 'Missed one run due to weather.',
    coach_comment: 'Great effort pushing through the new exercises. Missing one run due to rain is completely fine.',
    loom_url: null,
    submitted: true,
    created_at: '2026-02-18T08:00:00Z',
    photo_front_url: null,
    photo_side_url: null,
    photo_back_url: null,
  },
  // Jake Wilson
  {
    id: 'demo-ci-7',
    client_id: 'demo-client-3',
    date: '2026-03-02',
    energy: 8,
    stress: 3,
    sleep_quality: 8,
    training_difficulty: 9,
    digestion: null,
    bodyweight_kg: 81.5,
    wins: 'Bench press up to 110kg — strongest ever. Eating well and sleeping great.',
    struggles: 'Calorie intake was slightly under on rest days.',
    coach_comment: 'That bench is elite mate! On rest days it\'s still important to eat enough — your muscles grow outside the gym.',
    loom_url: null,
    submitted: true,
    created_at: '2026-03-02T07:30:00Z',
    photo_front_url: null,
    photo_side_url: null,
    photo_back_url: null,
  },
  {
    id: 'demo-ci-8',
    client_id: 'demo-client-3',
    date: '2026-02-23',
    energy: 7,
    stress: 4,
    sleep_quality: 7,
    training_difficulty: 8,
    digestion: null,
    bodyweight_kg: 81.0,
    wins: 'Scale weight going up steadily. All 4 sessions completed.',
    struggles: 'Getting enough carbs post-workout is tricky with my schedule.',
    coach_comment: 'The steady weight gain is exactly what we want. Try prepping a rice and chicken portion the night before for post-workout.',
    loom_url: null,
    submitted: true,
    created_at: '2026-02-23T07:30:00Z',
    photo_front_url: null,
    photo_side_url: null,
    photo_back_url: null,
  },
  // Emma Thompson
  {
    id: 'demo-ci-9',
    client_id: 'demo-client-4',
    date: '2026-03-05',
    energy: 7,
    stress: 4,
    sleep_quality: 8,
    training_difficulty: 5,
    digestion: null,
    bodyweight_kg: 69.0,
    wins: 'Did all 3 sessions for the first time ever! Feeling proud.',
    struggles: 'Still nervous about using the free weights area in the gym.',
    coach_comment: 'Emma this is a massive win — all 3 sessions is incredible for week 1. The gym nerves are 100% normal and will fade fast.',
    loom_url: null,
    submitted: true,
    created_at: '2026-03-05T09:00:00Z',
    photo_front_url: null,
    photo_side_url: null,
    photo_back_url: null,
  },
  {
    id: 'demo-ci-10',
    client_id: 'demo-client-4',
    date: '2026-02-26',
    energy: 6,
    stress: 5,
    sleep_quality: 7,
    training_difficulty: 4,
    digestion: null,
    bodyweight_kg: 69.5,
    wins: 'Tracked meals 5 out of 7 days — best week yet.',
    struggles: 'Weekend social eating made nutrition hard to manage.',
    coach_comment: 'Tracking 5 days is really solid progress Emma. For weekends, just try to make the best choice available — perfectionism is the enemy!',
    loom_url: null,
    submitted: true,
    created_at: '2026-02-26T09:00:00Z',
    photo_front_url: null,
    photo_side_url: null,
    photo_back_url: null,
  },
]

export const DEMO_WEIGHT_LOGS = [
  // Liam Carter — gradual fat loss with BF% tracked every ~6 weeks
  { id: 'demo-wl-1',  client_id: 'demo-client-1', weight_kg: 95.5, date: '2025-09-16', body_fat_pct: 28.4, notes: 'Starting weight', created_at: '2025-09-16T07:00:00Z' },
  { id: 'demo-wl-2',  client_id: 'demo-client-1', weight_kg: 94.8, date: '2025-10-01', body_fat_pct: null, notes: null, created_at: '2025-10-01T07:00:00Z' },
  { id: 'demo-wl-3',  client_id: 'demo-client-1', weight_kg: 93.9, date: '2025-10-15', body_fat_pct: null, notes: null, created_at: '2025-10-15T07:00:00Z' },
  { id: 'demo-wl-4',  client_id: 'demo-client-1', weight_kg: 93.0, date: '2025-11-01', body_fat_pct: 26.8, notes: null, created_at: '2025-11-01T07:00:00Z' },
  { id: 'demo-wl-5',  client_id: 'demo-client-1', weight_kg: 92.1, date: '2025-11-15', body_fat_pct: null, notes: null, created_at: '2025-11-15T07:00:00Z' },
  { id: 'demo-wl-6',  client_id: 'demo-client-1', weight_kg: 91.5, date: '2025-12-01', body_fat_pct: null, notes: null, created_at: '2025-12-01T07:00:00Z' },
  { id: 'demo-wl-7',  client_id: 'demo-client-1', weight_kg: 90.8, date: '2025-12-15', body_fat_pct: 25.1, notes: null, created_at: '2025-12-15T07:00:00Z' },
  { id: 'demo-wl-8',  client_id: 'demo-client-1', weight_kg: 90.2, date: '2026-01-07', body_fat_pct: null, notes: null, created_at: '2026-01-07T07:00:00Z' },
  { id: 'demo-wl-9',  client_id: 'demo-client-1', weight_kg: 89.8, date: '2026-01-21', body_fat_pct: null, notes: null, created_at: '2026-01-21T07:00:00Z' },
  { id: 'demo-wl-10', client_id: 'demo-client-1', weight_kg: 89.1, date: '2026-02-04', body_fat_pct: 23.6, notes: null, created_at: '2026-02-04T07:00:00Z' },
  { id: 'demo-wl-11', client_id: 'demo-client-1', weight_kg: 88.5, date: '2026-02-18', body_fat_pct: null, notes: null, created_at: '2026-02-18T07:00:00Z' },
  { id: 'demo-wl-12', client_id: 'demo-client-1', weight_kg: 88.2, date: '2026-03-03', body_fat_pct: 22.9, notes: null, created_at: '2026-03-03T07:00:00Z' },
  // Sophie Nguyen — gradual loss with BF% tracked
  { id: 'demo-wl-13', client_id: 'demo-client-2', weight_kg: 68.0, date: '2025-10-04', body_fat_pct: 30.2, notes: 'Starting weight', created_at: '2025-10-04T08:00:00Z' },
  { id: 'demo-wl-14', client_id: 'demo-client-2', weight_kg: 67.5, date: '2025-10-18', body_fat_pct: null, notes: null, created_at: '2025-10-18T08:00:00Z' },
  { id: 'demo-wl-15', client_id: 'demo-client-2', weight_kg: 67.0, date: '2025-11-01', body_fat_pct: null, notes: null, created_at: '2025-11-01T08:00:00Z' },
  { id: 'demo-wl-16', client_id: 'demo-client-2', weight_kg: 66.6, date: '2025-11-15', body_fat_pct: 28.8, notes: null, created_at: '2025-11-15T08:00:00Z' },
  { id: 'demo-wl-17', client_id: 'demo-client-2', weight_kg: 66.2, date: '2025-12-01', body_fat_pct: null, notes: null, created_at: '2025-12-01T08:00:00Z' },
  { id: 'demo-wl-18', client_id: 'demo-client-2', weight_kg: 65.8, date: '2025-12-15', body_fat_pct: null, notes: null, created_at: '2025-12-15T08:00:00Z' },
  { id: 'demo-wl-19', client_id: 'demo-client-2', weight_kg: 65.5, date: '2026-01-07', body_fat_pct: 27.4, notes: null, created_at: '2026-01-07T08:00:00Z' },
  { id: 'demo-wl-20', client_id: 'demo-client-2', weight_kg: 65.2, date: '2026-01-21', body_fat_pct: null, notes: null, created_at: '2026-01-21T08:00:00Z' },
  { id: 'demo-wl-21', client_id: 'demo-client-2', weight_kg: 65.0, date: '2026-02-04', body_fat_pct: null, notes: null, created_at: '2026-02-04T08:00:00Z' },
  { id: 'demo-wl-22', client_id: 'demo-client-2', weight_kg: 64.7, date: '2026-02-18', body_fat_pct: 26.1, notes: null, created_at: '2026-02-18T08:00:00Z' },
  { id: 'demo-wl-23', client_id: 'demo-client-2', weight_kg: 64.5, date: '2026-03-04', body_fat_pct: 25.6, notes: null, created_at: '2026-03-04T08:00:00Z' },
  // Jake Wilson — muscle gain, BF% stable then slight rise
  { id: 'demo-wl-24', client_id: 'demo-client-3', weight_kg: 78.0, date: '2025-11-19', body_fat_pct: 14.2, notes: 'Starting weight', created_at: '2025-11-19T07:30:00Z' },
  { id: 'demo-wl-25', client_id: 'demo-client-3', weight_kg: 78.5, date: '2025-12-03', body_fat_pct: null, notes: null, created_at: '2025-12-03T07:30:00Z' },
  { id: 'demo-wl-26', client_id: 'demo-client-3', weight_kg: 79.0, date: '2025-12-17', body_fat_pct: 14.5, notes: null, created_at: '2025-12-17T07:30:00Z' },
  { id: 'demo-wl-27', client_id: 'demo-client-3', weight_kg: 79.5, date: '2026-01-07', body_fat_pct: null, notes: null, created_at: '2026-01-07T07:30:00Z' },
  { id: 'demo-wl-28', client_id: 'demo-client-3', weight_kg: 80.0, date: '2026-01-21', body_fat_pct: 14.9, notes: null, created_at: '2026-01-21T07:30:00Z' },
  { id: 'demo-wl-29', client_id: 'demo-client-3', weight_kg: 80.5, date: '2026-02-04', body_fat_pct: null, notes: null, created_at: '2026-02-04T07:30:00Z' },
  { id: 'demo-wl-30', client_id: 'demo-client-3', weight_kg: 81.0, date: '2026-02-18', body_fat_pct: 15.1, notes: null, created_at: '2026-02-18T07:30:00Z' },
  { id: 'demo-wl-31', client_id: 'demo-client-3', weight_kg: 81.5, date: '2026-03-02', body_fat_pct: 15.2, notes: null, created_at: '2026-03-02T07:30:00Z' },
  // Emma Thompson — gradual loss with BF% tracked
  { id: 'demo-wl-32', client_id: 'demo-client-4', weight_kg: 72.5, date: '2025-12-02', body_fat_pct: 34.1, notes: 'Starting weight', created_at: '2025-12-02T09:00:00Z' },
  { id: 'demo-wl-33', client_id: 'demo-client-4', weight_kg: 71.8, date: '2025-12-16', body_fat_pct: null, notes: null, created_at: '2025-12-16T09:00:00Z' },
  { id: 'demo-wl-34', client_id: 'demo-client-4', weight_kg: 71.2, date: '2026-01-07', body_fat_pct: 32.8, notes: null, created_at: '2026-01-07T09:00:00Z' },
  { id: 'demo-wl-35', client_id: 'demo-client-4', weight_kg: 70.6, date: '2026-01-21', body_fat_pct: null, notes: null, created_at: '2026-01-21T09:00:00Z' },
  { id: 'demo-wl-36', client_id: 'demo-client-4', weight_kg: 70.1, date: '2026-02-04', body_fat_pct: 31.5, notes: null, created_at: '2026-02-04T09:00:00Z' },
  { id: 'demo-wl-37', client_id: 'demo-client-4', weight_kg: 69.5, date: '2026-02-18', body_fat_pct: null, notes: null, created_at: '2026-02-18T09:00:00Z' },
  { id: 'demo-wl-38', client_id: 'demo-client-4', weight_kg: 69.0, date: '2026-03-05', body_fat_pct: 30.2, notes: null, created_at: '2026-03-05T09:00:00Z' },
]

export const DEMO_NOTES = [
  // Liam Carter
  {
    id: 'demo-note-1',
    coach_id: 'demo-coach-1',
    client_id: 'demo-client-1',
    content: 'Great attitude and coachability. Responds well to progressive overload. Focus on keeping lower back neutral during all hinge movements.',
    is_pinned: true,
    created_at: '2025-09-20T10:00:00Z',
    updated_at: '2025-09-20T10:00:00Z',
  },
  {
    id: 'demo-note-2',
    coach_id: 'demo-coach-1',
    client_id: 'demo-client-1',
    content: 'Discussed nutrition strategy for weekend social events. Told him to prioritise protein and not stress about one off-plan meal.',
    is_pinned: false,
    created_at: '2025-11-05T09:30:00Z',
    updated_at: '2025-11-05T09:30:00Z',
  },
  {
    id: 'demo-note-3',
    coach_id: 'demo-coach-1',
    client_id: 'demo-client-1',
    content: 'Consider moving to a 5-day program next block. He\'s adapted well to 4 days and is asking for more volume.',
    is_pinned: false,
    created_at: '2026-01-15T08:00:00Z',
    updated_at: '2026-01-15T08:00:00Z',
  },
  // Sophie Nguyen
  {
    id: 'demo-note-4',
    coach_id: 'demo-coach-1',
    client_id: 'demo-client-2',
    content: 'Very strong aerobic base from running. Needs to build lower body strength to reduce injury risk as mileage increases.',
    is_pinned: true,
    created_at: '2025-10-10T09:00:00Z',
    updated_at: '2025-10-10T09:00:00Z',
  },
  {
    id: 'demo-note-5',
    coach_id: 'demo-coach-1',
    client_id: 'demo-client-2',
    content: 'Gluten intolerance confirmed — needs to double check all sauces and condiments when eating out.',
    is_pinned: false,
    created_at: '2025-10-25T10:00:00Z',
    updated_at: '2025-10-25T10:00:00Z',
  },
  {
    id: 'demo-note-6',
    coach_id: 'demo-coach-1',
    client_id: 'demo-client-2',
    content: 'Half marathon target race is May 2026. Structure training load to peak for that event.',
    is_pinned: false,
    created_at: '2026-02-01T08:30:00Z',
    updated_at: '2026-02-01T08:30:00Z',
  },
  // Jake Wilson
  {
    id: 'demo-note-7',
    coach_id: 'demo-coach-1',
    client_id: 'demo-client-3',
    content: 'Strong baseline — bench 100kg, squat 130kg, deadlift 160kg at start. Track these closely for PB milestones.',
    is_pinned: true,
    created_at: '2025-11-22T07:00:00Z',
    updated_at: '2025-11-22T07:00:00Z',
  },
  {
    id: 'demo-note-8',
    coach_id: 'demo-coach-1',
    client_id: 'demo-client-3',
    content: 'Works shift work — training schedule needs flexibility. Agreed on morning sessions when possible.',
    is_pinned: false,
    created_at: '2025-12-10T08:00:00Z',
    updated_at: '2025-12-10T08:00:00Z',
  },
  // Emma Thompson
  {
    id: 'demo-note-9',
    coach_id: 'demo-coach-1',
    client_id: 'demo-client-4',
    content: 'First-time gym goer. Needs extra encouragement and clear instructions. Prioritise technique before loading.',
    is_pinned: true,
    created_at: '2025-12-05T10:00:00Z',
    updated_at: '2025-12-05T10:00:00Z',
  },
  {
    id: 'demo-note-10',
    coach_id: 'demo-coach-1',
    client_id: 'demo-client-4',
    content: 'Energy levels improve significantly when she eats breakfast — remind her every check-in.',
    is_pinned: false,
    created_at: '2026-01-10T09:00:00Z',
    updated_at: '2026-01-10T09:00:00Z',
  },
]

export const DEMO_PROGRAMS = [
  {
    id: 'demo-prog-1',
    client_id: 'demo-client-1',
    coach_id: 'demo-coach-1',
    name: 'Fat Loss Hypertrophy Block',
    description: 'Upper/lower split focused on preserving muscle while in a calorie deficit.',
    goal: 'Fat loss with muscle retention',
    weeks: 8,
    current_week: 5,
    days_per_week: 4,
    is_active: true,
    ai_generated: false,
    coach_approved: true,
    created_at: '2025-11-01T08:00:00Z',
    updated_at: '2026-01-20T08:00:00Z',
  },
  {
    id: 'demo-prog-2',
    client_id: 'demo-client-2',
    coach_id: 'demo-coach-1',
    name: 'Run-Strength Hybrid Program',
    description: 'Combines structured running schedule with 2x per week strength sessions to support half marathon prep.',
    goal: 'Half marathon performance + general strength',
    weeks: 12,
    current_week: 9,
    days_per_week: 5,
    is_active: true,
    ai_generated: false,
    coach_approved: true,
    created_at: '2025-10-15T09:00:00Z',
    updated_at: '2026-01-10T09:00:00Z',
  },
  {
    id: 'demo-prog-3',
    client_id: 'demo-client-3',
    coach_id: 'demo-coach-1',
    name: 'Hypertrophy Bulk Block',
    description: 'Push/pull/legs split designed for maximum muscle growth. High volume, progressive overload.',
    goal: 'Muscle gain and strength increase',
    weeks: 10,
    current_week: 4,
    days_per_week: 4,
    is_active: true,
    ai_generated: false,
    coach_approved: true,
    created_at: '2025-12-01T07:00:00Z',
    updated_at: '2026-02-01T07:00:00Z',
  },
  {
    id: 'demo-prog-4',
    client_id: 'demo-client-4',
    coach_id: 'demo-coach-1',
    name: 'Beginner Foundation Program',
    description: 'Full body 3x per week program to build movement patterns and habits.',
    goal: 'Habit formation and general fitness',
    weeks: 6,
    current_week: 2,
    days_per_week: 3,
    is_active: true,
    ai_generated: false,
    coach_approved: true,
    created_at: '2026-01-20T10:00:00Z',
    updated_at: '2026-02-15T10:00:00Z',
  },
]

export const DEMO_MACRO_TARGETS = [
  {
    id: 'demo-macro-1',
    client_id: 'demo-client-1',
    calories: 2400,
    protein_g: 190,
    carbs_g: 240,
    fats_g: 75,
    fibre_g: 35,
    water_ml: 3000,
    set_by_coach: true,
    coach_notes: 'Moderate deficit. Keep protein high to preserve muscle.',
    created_at: '2025-09-18T08:00:00Z',
    updated_at: '2025-11-01T08:00:00Z',
  },
  {
    id: 'demo-macro-2',
    client_id: 'demo-client-2',
    calories: 1950,
    protein_g: 140,
    carbs_g: 210,
    fats_g: 60,
    fibre_g: 30,
    water_ml: 2500,
    set_by_coach: true,
    coach_notes: 'Slight deficit. Carbs timed around runs for performance.',
    created_at: '2025-10-06T09:00:00Z',
    updated_at: '2025-12-01T09:00:00Z',
  },
  {
    id: 'demo-macro-3',
    client_id: 'demo-client-3',
    calories: 3200,
    protein_g: 200,
    carbs_g: 380,
    fats_g: 90,
    fibre_g: 40,
    water_ml: 3500,
    set_by_coach: true,
    coach_notes: 'Calorie surplus for lean bulk. Monitor weight gain weekly.',
    created_at: '2025-11-20T07:00:00Z',
    updated_at: '2026-01-05T07:00:00Z',
  },
  {
    id: 'demo-macro-4',
    client_id: 'demo-client-4',
    calories: 1800,
    protein_g: 120,
    carbs_g: 180,
    fats_g: 65,
    fibre_g: 25,
    water_ml: 2000,
    set_by_coach: true,
    coach_notes: 'Gentle deficit. Focus on hitting protein and eating whole foods.',
    created_at: '2025-12-05T10:00:00Z',
    updated_at: '2026-01-10T10:00:00Z',
  },
]

// ── NEW DEMO DATA ──

export const DEMO_MEAL_PLANS: MealPlan[] = [
  {
    id: 'demo-mp-1',
    coach_id: 'demo-coach-1',
    client_id: 'demo-client-1',
    name: 'Liam — Fat Loss Meal Plan',
    description: '7-day high protein meal plan in a moderate calorie deficit.',
    plan_type: 'meal',
    calories_target: 2400,
    protein_target: 190,
    carbs_target: 240,
    fats_target: 75,
    is_template: false,
    created_at: '2025-11-05T08:00:00Z',
    updated_at: '2025-11-05T08:00:00Z',
  },
  {
    id: 'demo-mp-2',
    coach_id: 'demo-coach-1',
    client_id: 'demo-client-2',
    name: 'Sophie — Vegetarian Performance Plan',
    description: 'Gluten-free vegetarian plan with carbs timed around training sessions.',
    plan_type: 'meal',
    calories_target: 1950,
    protein_target: 140,
    carbs_target: 210,
    fats_target: 60,
    is_template: false,
    created_at: '2025-10-10T09:00:00Z',
    updated_at: '2025-10-10T09:00:00Z',
  },
  {
    id: 'demo-mp-3',
    coach_id: 'demo-coach-1',
    client_id: 'demo-client-3',
    name: 'Jake — Bulk Macros Plan',
    description: 'High calorie macros plan structured for lean muscle gain.',
    plan_type: 'macros',
    calories_target: 3200,
    protein_target: 200,
    carbs_target: 380,
    fats_target: 90,
    is_template: false,
    created_at: '2025-11-25T07:00:00Z',
    updated_at: '2025-11-25T07:00:00Z',
  },
]

export const DEMO_TASKS: Task[] = [
  {
    id: 'demo-task-1',
    coach_id: 'demo-coach-1',
    client_id: 'demo-client-1',
    title: 'Review Liam\'s weekly check-in',
    description: 'Check his energy and sleep scores and update program if needed.',
    due_date: '2026-03-10',
    completed: false,
    priority: 'high',
    created_at: '2026-03-08T08:00:00Z',
  },
  {
    id: 'demo-task-2',
    coach_id: 'demo-coach-1',
    client_id: 'demo-client-2',
    title: 'Build Sophie\'s next training block',
    description: '12-week peak phase leading into her May half marathon.',
    due_date: '2026-03-15',
    completed: false,
    priority: 'high',
    created_at: '2026-03-05T09:00:00Z',
  },
  {
    id: 'demo-task-3',
    coach_id: 'demo-coach-1',
    client_id: 'demo-client-3',
    title: 'Update Jake\'s macro targets',
    description: 'He\'s gained 3.5kg — consider a slight increase in calories.',
    due_date: '2026-03-11',
    completed: false,
    priority: 'medium',
    created_at: '2026-03-07T10:00:00Z',
  },
  {
    id: 'demo-task-4',
    coach_id: 'demo-coach-1',
    client_id: 'demo-client-4',
    title: 'Send Emma her first meal plan',
    description: 'Keep it simple — 3 meals + 1 snack. High protein, balanced carbs.',
    due_date: '2026-03-10',
    completed: false,
    priority: 'medium',
    created_at: '2026-03-06T11:00:00Z',
  },
  {
    id: 'demo-task-5',
    coach_id: 'demo-coach-1',
    client_id: null,
    title: 'Update onboarding questionnaire',
    description: 'Add injury history section and dietary allergy field.',
    due_date: '2026-03-20',
    completed: false,
    priority: 'low',
    created_at: '2026-03-01T08:00:00Z',
  },
  {
    id: 'demo-task-6',
    coach_id: 'demo-coach-1',
    client_id: 'demo-client-1',
    title: 'Check in call with Liam',
    description: 'Monthly video call to review progress and set next month goals.',
    due_date: '2026-03-17',
    completed: false,
    priority: 'medium',
    created_at: '2026-03-03T09:00:00Z',
  },
  {
    id: 'demo-task-7',
    coach_id: 'demo-coach-1',
    client_id: null,
    title: 'Post weekly content to Instagram',
    description: 'Training tips reel + nutrition myth-busting carousel.',
    due_date: '2026-03-08',
    completed: true,
    priority: 'low',
    created_at: '2026-03-01T10:00:00Z',
  },
  {
    id: 'demo-task-8',
    coach_id: 'demo-coach-1',
    client_id: 'demo-client-2',
    title: 'Review Sophie\'s race-day nutrition strategy',
    description: 'Help her plan fuelling for the half marathon in May.',
    due_date: '2026-04-01',
    completed: false,
    priority: 'low',
    created_at: '2026-03-05T08:30:00Z',
  },
  {
    id: 'demo-task-9',
    coach_id: 'demo-coach-1',
    client_id: 'demo-client-4',
    title: 'Follow up with Emma about gym anxiety',
    description: 'Check if she\'s feeling more comfortable in the free weights area.',
    due_date: '2026-03-12',
    completed: false,
    priority: 'high',
    created_at: '2026-03-05T09:30:00Z',
  },
  {
    id: 'demo-task-10',
    coach_id: 'demo-coach-1',
    client_id: 'demo-client-3',
    title: 'Log Jake\'s new bench press PB',
    description: '110kg for 3 reps. Calculate estimated 1RM and update records.',
    due_date: '2026-03-02',
    completed: true,
    priority: 'medium',
    created_at: '2026-03-02T08:00:00Z',
  },
]

export const DEMO_AUTOFLOWS: Autoflow[] = [
  {
    id: 'demo-af-1',
    coach_id: 'demo-coach-1',
    client_id: null,
    name: 'New Client Onboarding',
    trigger_type: 'event',
    trigger_day: null,
    events: [
      {
        id: 'demo-afe-1',
        autoflow_id: 'demo-af-1',
        event_type: 'workout_program',
        day_offset: 1,
        payload: { program_id: 'demo-prog-4' },
        created_at: '2025-12-01T08:00:00Z',
      },
      {
        id: 'demo-afe-2',
        autoflow_id: 'demo-af-1',
        event_type: 'resources',
        day_offset: 1,
        payload: { resource_type: 'welcome_pack' },
        created_at: '2025-12-01T08:00:00Z',
      },
      {
        id: 'demo-afe-3',
        autoflow_id: 'demo-af-1',
        event_type: 'message',
        day_offset: 3,
        payload: { message: 'Hey! Just checking in — how are you finding the first few sessions?' },
        created_at: '2025-12-01T08:00:00Z',
      },
    ],
    is_active: true,
    created_at: '2025-12-01T08:00:00Z',
  },
  {
    id: 'demo-af-2',
    coach_id: 'demo-coach-1',
    client_id: 'demo-client-1',
    name: 'Liam — Weekly Check-in Reminder',
    trigger_type: 'day',
    trigger_day: 7,
    events: [
      {
        id: 'demo-afe-4',
        autoflow_id: 'demo-af-2',
        event_type: 'notification',
        day_offset: 0,
        payload: { message: 'Time for your weekly check-in! Let your coach know how the week went.' },
        created_at: '2025-10-01T08:00:00Z',
      },
    ],
    is_active: true,
    created_at: '2025-10-01T08:00:00Z',
  },
  {
    id: 'demo-af-3',
    coach_id: 'demo-coach-1',
    client_id: null,
    name: 'Program Block Transition',
    trigger_type: 'day',
    trigger_day: 56,
    events: [
      {
        id: 'demo-afe-5',
        autoflow_id: 'demo-af-3',
        event_type: 'note',
        day_offset: 0,
        payload: { note: 'Great work completing the 8-week block! Your new program is ready.' },
        created_at: '2025-11-01T08:00:00Z',
      },
      {
        id: 'demo-afe-6',
        autoflow_id: 'demo-af-3',
        event_type: 'workout_program',
        day_offset: 1,
        payload: {},
        created_at: '2025-11-01T08:00:00Z',
      },
    ],
    is_active: false,
    created_at: '2025-11-01T08:00:00Z',
  },
]

export const DEMO_PRS: Record<string, { exercise: string; weight: number; reps: number; e1rm: number; date: string }[]> = {
  'demo-client-1': [
    { exercise: 'Squat', weight: 120, reps: 5, e1rm: 139, date: '2026-03-03' },
    { exercise: 'Bench Press', weight: 100, reps: 5, e1rm: 116, date: '2026-02-10' },
    { exercise: 'Romanian Deadlift', weight: 110, reps: 6, e1rm: 131, date: '2026-01-28' },
  ],
  'demo-client-2': [
    { exercise: 'Bulgarian Split Squat', weight: 40, reps: 8, e1rm: 51, date: '2026-02-18' },
    { exercise: 'Hip Thrust', weight: 90, reps: 10, e1rm: 120, date: '2026-03-04' },
  ],
  'demo-client-3': [
    { exercise: 'Bench Press', weight: 110, reps: 3, e1rm: 123, date: '2026-03-02' },
    { exercise: 'Deadlift', weight: 175, reps: 3, e1rm: 195, date: '2026-02-16' },
    { exercise: 'Squat', weight: 140, reps: 5, e1rm: 163, date: '2026-01-20' },
  ],
  'demo-client-4': [
    { exercise: 'Goblet Squat', weight: 24, reps: 10, e1rm: 32, date: '2026-03-05' },
  ],
}
