-- Exercise seed data — Batch 9
-- Active Aging, Chronic Condition Management & Metabolic/EPOC Conditioning
-- Balance & fall prevention, arthritis-friendly, chair-based, Zone 2, EPOC protocols

insert into exercises (name, primary_muscle_group, secondary_muscle_groups, muscle_groups, category, movement_type, equipment, difficulty_level, is_compound, instructions, common_mistakes, subcategory, coaching_cues, progressions, regressions, tags, contraindications, force_type, plane_of_motion, is_unilateral, sets_default, reps_default, duration_seconds, rest_seconds, is_system) values

-- ─── BALANCE & FALL PREVENTION (SENIORS) ─────────────────────────────────────
('Single-Leg Stand (Balance Training)',
 'core', array['quadriceps','glutes','ankle_stabilisers'], array['core','quadriceps'],
 'functional', 'other', array['bodyweight'], 'beginner', false,
 'Stand near a wall or sturdy chair for safety. Lift one foot slightly off the floor (2-5 cm). Hold the balance for up to 30 seconds. Eyes open first, then progress to eyes closed (dramatically harder — removes visual balance cues). The ability to stand on one leg for 10 seconds is associated with significantly better long-term health outcomes in adults over 50. This exercise activates the ankle stabilisers (tibialis anterior, peroneals), knee stabilisers, hip abductors, and core all simultaneously. Practice daily.',
 'Holding breath (makes balance harder — breathe normally); gripping the chair or wall unnecessarily when the goal is to balance without support; looking down at the feet (look forward at a fixed point); progressing to eyes closed before achieving 30 seconds eyes open.',
 'active_aging', array['Fixed gaze: eyes on a point on the wall at eye level','Breathe normally: breath holding makes it harder','30 seconds first: achieve this before progressing to eyes closed','Touch the wall only if falling: the goal is unsupported balance'],
 array['Eyes-closed single-leg stand','Single-leg stand on a foam pad (reduced stability)','Single-leg stand while performing arm movements'],
 array['Stand with two feet together','Weight shift side-to-side','Heel-to-toe standing'],
 array['active_aging','balance','fall_prevention','seniors','single_leg','stability'], array['peripheral_neuropathy_severe','acute_vestibular_disorder'],
 'isometric', 'frontal', true, 3, null, 30, 30, true),

('Tandem Walk (Tightrope Walking)',
 'core', array['ankle_stabilisers','hip_abductors'], array['core'],
 'functional', 'other', array['bodyweight'], 'beginner', false,
 'Walk in a straight line placing the heel of the front foot directly in front of the toes of the back foot (heel-to-toe). Arms extend out to the sides for balance. Take 20 steps, then turn and return. Use a line of tape on the floor or walk along a hallway wall. This gait pattern challenges dynamic balance and exposes instability in the hip abductors, ankle stabilisers, and core. Falls in older adults predominantly occur during movement transitions — tandem walking trains exactly this. Progress: increase speed, remove the wall, walk backwards.',
 'Looking down at the feet (look forward or use a wall mirror); taking steps that are too long (smaller steps are safer); not using outstretched arms for balance; progressing to rapid speed before achieving controlled slow tandem walking.',
 'active_aging', array['Look forward: do not look at your feet','Slow first: control beats speed','Arms out: they are your balance aids','Wall nearby: safety first — especially when beginning'],
 array['Tandem walk on foam mat (less stable surface)','Tandem walk with head turns (visual disturbance)','Tandem walk backwards'],
 array['Side-to-side weight shift standing','Standing with feet hip-width and eyes closed','Heel raises bilateral standing'],
 array['active_aging','balance','tandem_walk','dynamic_balance','fall_prevention','gait'], array['peripheral_neuropathy_severe','acute_vestibular_disorder','acute_lower_limb_injury'],
 'locomotion', 'sagittal', false, 3, null, 60, 60, true),

('Sit-to-Stand (Chair Rise Test & Training)',
 'quadriceps', array['glutes','hamstrings','core'], array['quadriceps','glutes'],
 'functional', 'strength', array['chair'], 'beginner', true,
 'The sit-to-stand is both a fundamental exercise AND a validated functional test (Five Times Sit to Stand Test). Exercise: sit in a firm chair with feet flat, arms crossed on the chest. Stand up to full height, then lower back to the seat under control. Repeat 10-15 times per set. The 30-Second Chair Stand Test (count how many in 30 seconds) is used to monitor progress. Inability to perform this exercise without arm assistance is associated with fall risk and reduced independence. One of the most functional exercises for older adults — it directly translates to daily activities.',
 'Using arms to push off the chair (upper limbs assist — should be arms crossed on chest for the exercise); falling back into the chair (the eccentric lowering is as important as the standing up); leaning too far forward before rising (weight should be over the feet, not excessively forward).',
 'active_aging', array['Arms crossed: no pushing off with hands','Slow lowering: control the descent — do not fall back','Weight over feet: lean forward just enough to get weight over the feet','Functional: this is getting up from a chair — make it exactly like daily life'],
 array['Sit-to-stand with weighted vest','Single-leg sit-to-stand (much harder)','Step-up as next progression'],
 array['Sit-to-stand using arm support','Sit-to-stand from a higher chair (easier)','Rocking forward from chair as a start'],
 array['active_aging','functional','sit_to_stand','fall_prevention','independence','quadriceps'], array['severe_hip_osteoarthritis','total_hip_replacement_recent'],
 'push', 'sagittal', false, 3, 12, null, 60, true),

('Stepping Exercises (Lateral & Forward)',
 'quadriceps', array['glutes','hip_abductors','core'], array['quadriceps','glutes'],
 'functional', 'other', array['bodyweight','step'], 'beginner', false,
 'Three step patterns for fall prevention and functional mobility: (1) Forward step — step forward with one foot, step back; alternate 10 each side. (2) Lateral step — step sideways to the right, bring feet together, step right again for 5 steps; return. (3) Step-up — step up onto a step (15-20 cm), bring both feet up, step back down. All stepping patterns improve reactive balance and train the coordination needed to prevent falls when navigating uneven terrain, stairs, and obstacles. Use a wall nearby for safety. The step-up specifically strengthens the quadriceps for stair climbing.',
 'Moving too quickly and losing balance; not having a safety support nearby; using a step that is too high initially; not completing the full weight-transfer before taking the next step (rushing through the weight shift).',
 'active_aging', array['Complete the weight transfer: full weight onto the stepping foot before moving again','Wall nearby: not used unless needed — challenge the balance','Lateral step: often neglected — the mediolateral fall direction is most dangerous','Slow and deliberate: control is the goal, not speed'],
 array['Step-up with knee drive at the top','Lateral step with mini-band resistance','Step sequence patterns (forward/backward/lateral combined)'],
 array['Weight shift side-to-side without steps','Marching on the spot with hip flexion','Stepping forward and back holding a support'],
 array['active_aging','balance','stepping','fall_prevention','functional','stair_training'], array['acute_ankle_sprain','severe_knee_osteoarthritis'],
 'push', 'sagittal', false, 3, 10, null, 60, true),

('Functional Reach Test & Training',
 'core', array['shoulder','hip_stabilisers'], array['core','shoulder'],
 'functional', 'other', array['bodyweight'], 'beginner', false,
 'Stand near a wall with feet shoulder-width, arm extended at shoulder height. Without moving the feet, reach forward as far as possible. The distance from start to finish is the functional reach score: less than 15 cm = significant fall risk; 15-25 cm = moderate; greater than 25 cm = low risk. Exercise: practice reaching in all directions — forward, diagonal, to the side — progressively challenging the base of support. Also: reach while standing on one leg (dramatically harder). This specifically trains the anticipatory postural responses that prevent falls.',
 'Moving the feet or taking a step during the reach (the whole point is maintaining a fixed base of support); holding the breath; not reaching far enough to challenge the limits of the base of support.',
 'active_aging', array['Feet fixed: do not let them move or step','Breathe through: relaxed breathing during the reach','Challenge the limits: easy reaches do not improve balance','Diagonal reach: forward/sideways combined creates the greatest challenge'],
 array['Multi-directional reach training program','Reach while performing secondary task (cognitive load)','Reach on a foam pad for greater instability'],
 array['Seated reach training (chair)','Two-hands reach with support','Stationary standing balance only'],
 array['active_aging','balance','functional_reach','fall_prevention','anticipatory_control','assessment'], array['severe_postural_hypotension','vestibular_disorder_acute'],
 'isometric', 'multi', false, 3, 10, null, 45, true),

-- ─── CHAIR-BASED EXERCISES ────────────────────────────────────────────────────
('Chair-Based Strength Circuit (Full Body)',
 'quadriceps', array['glutes','back','shoulder','core'], array['quadriceps','glutes','back'],
 'functional', 'strength', array['chair','resistance_band','dumbbell'], 'beginner', false,
 'Full-body circuit performed seated in a sturdy chair. Exercises: (1) Seated marching — alternating knee lifts, 20 reps; (2) Seated arm raise — lift dumbbells or bands overhead, 15 reps; (3) Seated row with band — loop band around feet and row, 15 reps; (4) Seated leg extension — straighten one leg and hold 2 seconds, 12 per leg; (5) Seated side bend — reach one arm toward the floor, 10 per side; (6) Seated chest press with band — 15 reps; (7) Seated heel raises — both heels rise, 20 reps. Complete 2 circuits. For people with very limited mobility, severe obesity, or high fall risk — these exercises provide full-body stimulus from a completely safe position.',
 'Using a chair with wheels (must use a stable, non-wheeled chair — this is a safety issue); rushing through exercises (slow tempo is recommended for muscle development and awareness); not anchoring the band safely.',
 'active_aging', array['Stable chair: four legs, no wheels, against a wall','Slow tempo: 3 counts up, 3 counts down for all movements','Resistance band anchor: loop under the feet or around the chair legs safely','Full body: hitting every major muscle group across the 7 exercises'],
 array['Add light dumbbells to all seated exercises','Combine seated and standing exercises','Progress to partially supported standing exercises'],
 array['Breathing exercises seated only','Seated range of motion exercises only','Passive stretching in the chair'],
 array['active_aging','chair_based','seated','full_body','circuit','limited_mobility','safe'], array[],
 'mixed', 'multi', false, 2, null, 1200, 60, true),

('Chair Yoga (Seated Flexibility & Mindfulness)',
 'core', array['hip_flexors','back','shoulder'], array['core','back'],
 'yoga_pilates', 'flexibility', array['chair'], 'beginner', false,
 'Chair yoga adapts classical yoga poses to a seated position. Sequence: (1) Seated mountain pose — sit tall, feet flat, hands on thighs, breathe deeply; (2) Seated forward fold — hinge forward over the thighs, arms hanging down; (3) Seated spinal twist — cross one arm over the opposite knee, look behind; (4) Seated eagle arms — wrap arms for shoulder stretch; (5) Seated warrior — extend one leg forward, arms out; (6) Seated cat-cow; (7) Seated breathing and relaxation. Chair yoga reduces pain, improves flexibility, reduces anxiety, and is accessible to people who cannot perform floor exercises.',
 'Using a chair with arms that restrict movement; performing poses with pain (the pose should be modified until it is comfortable — never painful); rushing between poses without taking the full breath.',
 'active_aging', array['Pain-free: every pose is modifiable — never push through joint pain','Breathe: each pose is held for 3-5 breaths','Sit tall first: mountain pose foundation is correct posture','Transition slowly: pause and breathe between poses'],
 array['Regular yoga class (if mobility progresses enough)','Chair yoga with resistance band additions','Chair yoga standing hybrid class'],
 array['Seated breathing only','Gentle seated range-of-motion exercises','Passive stretching in the chair'],
 array['active_aging','chair_yoga','flexibility','mindfulness','pain_management','mental_health'], array[],
 'isometric', 'multi', false, 1, null, 1800, null, true),

-- ─── ARTHRITIS-FRIENDLY EXERCISE ─────────────────────────────────────────────
('Osteoarthritis – Aquatic Therapy Program',
 'quadriceps', array['glutes','core','shoulder'], array['quadriceps','glutes'],
 'rehab', 'other', array['pool'], 'beginner', false,
 'Hydrotherapy (aquatic therapy) is among the most evidence-supported interventions for osteoarthritis of the hip, knee, and spine. In chest-deep water: (1) Water walking forward and backward — 5 minutes. (2) Side steps — 3 minutes. (3) Aqua cycling motion (legs simulating cycling) — 5 minutes. (4) Water-resisted leg swings forward/back and side/side — 3 minutes. (5) Underwater squats to comfortable range — 3×15. (6) Pool wall push-ups. Warm water (33-36°C) provides additional pain relief through muscle relaxation. Buoyancy reduces joint load by 50-90% allowing pain-free movement that is impossible on land.',
 'Water that is too cold (increases joint stiffness — warm water is essential for arthritis hydrotherapy); exercising in pain rather than in comfortable range (hydrotherapy should be pain-free or minimal pain); exiting the pool without assistance when joints are warm and potentially less stable (use the pool stairs with railing).',
 'arthritis', array['Warm water: 33-36°C is the therapeutic range for arthritis','Pain-free range: never push through pain — modify depth and range','Full body: the buoyancy allows movement of all joints without full weight-bearing','Consistency: hydrotherapy benefits accumulate with twice-weekly practice'],
 array['Aqua jogging with flotation belt','Swimming lap program','Hydrotherapy with resistance tools (pool noodles, paddles)'],
 array['Warm pool walking only','Passive warm water immersion and range of motion only','Land-based seated exercise if pool unavailable'],
 array['active_aging','arthritis','osteoarthritis','aquatic','hydrotherapy','pain_management','joint_friendly'], array['open_wounds','active_infection'],
 'mixed', 'multi', false, 1, null, 2400, null, true),

('Rheumatoid Arthritis – Energy Conservation Exercise',
 'core', array['quadriceps','glutes','shoulder'], array['core','quadriceps'],
 'rehab', 'other', array['bodyweight','resistance_band','chair'], 'beginner', false,
 'Rheumatoid arthritis (RA) requires exercise adaptation based on disease activity. During flares: rest the affected joints, maintain gentle range of motion only. Between flares: aerobic exercise and strength training reduce joint swelling, improve function, and reduce fatigue. Energy conservation principles: (1) Plan: schedule exercise at peak energy times (often morning after medication takes effect). (2) Prioritise: focus on the most functional exercises. (3) Pace: rest-activity-rest cycles prevent fatigue. (4) Position: choose joint-friendly positions (seated, water-based). Exercise in RA does NOT worsen joint damage — it reduces it.',
 'Exercising through a flare (during an active flare, rest is appropriate — gentle ROM only, not strengthening); stopping exercise entirely between flares (deconditioning accelerates functional decline); not communicating with the rheumatologist (medication changes affect exercise capacity).',
 'arthritis', array['Flare vs remission: different programs for different disease states','Morning timing: peak medication effect often in the morning','Gentle always: use 4/10 pain or less as the rule for RA exercise','Rheumatologist collaboration: exercise choices should be made with the medical team'],
 array['Pool-based exercise for joint protection during activity','Moderate intensity aerobic training during remission','Strength training with resistance bands in remission'],
 array['Gentle range of motion only during flares','Breathing and relaxation practice','Gentle warm water soaking for joint pain management'],
 array['active_aging','rheumatoid_arthritis','energy_conservation','flare_management','joint_protection'], array['active_joint_flare_severe'],
 'mixed', 'multi', false, 2, null, 1200, 60, true),

('Arthritis-Friendly Strength Training (Joints First)',
 'quadriceps', array['glutes','back','shoulder'], array['quadriceps','glutes'],
 'strength', 'strength', array['resistance_band','dumbbell','machine'], 'beginner', false,
 'Strength training is RECOMMENDED for osteoarthritis and rheumatoid arthritis — it reduces pain, improves function, and slows cartilage degradation. Joint-protective principles: (1) Machines over free weights (guided path reduces joint stress from instability). (2) Avoid the end range of motion in painful positions (3/4 range is fine). (3) Use higher reps and lower loads initially (15-20 reps at 40-50% 1RM). (4) Progress load gradually (5-10% per week). (5) Warm up the joints before loading (5-10 minutes of gentle movement). (6) Acceptable pain: 0-3/10 during and returning to baseline within 24 hours after exercise.',
 'Avoiding all strength training due to pain fear (deconditioning worsens arthritis pain in the long run); training through severe pain (3+/10); not warming up before loading; using full range of motion when half or three-quarter range is pain-free.',
 'arthritis', array['0-3/10 pain rule: mild discomfort during exercise is acceptable','Machines first: guided path protects arthritic joints better than free weights','Warm up the joints: 5-10 minutes of gentle movement before any loading','24-hour recovery rule: pain should return to baseline within 24 hours — if not, reduce load'],
 array['Progressive resistance training program','Pool-based resistance training','Moderate-intensity full body program for arthritis'],
 array['Range of motion exercises only','Chair-based exercises with zero load','Pool walking without resistance'],
 array['active_aging','arthritis','strength_training','joint_protection','pain_management','osteoarthritis'], array['joint_replacement_recent_3_months'],
 'mixed', 'multi', false, 3, 15, null, 60, true),

-- ─── CHRONIC DISEASE MANAGEMENT ──────────────────────────────────────────────
('Type 2 Diabetes – Post-Meal Walk (Glucose Management)',
 'cardiovascular', array['quadriceps','glutes'], array['cardiovascular','quadriceps'],
 'cardio', 'other', array['bodyweight'], 'beginner', false,
 'A 10-15 minute brisk walk within 30 minutes of a meal reduces postprandial (post-meal) blood glucose by 30-40% — superior to a 30-minute walk at any other time. Mechanism: muscle contraction stimulates glucose uptake via a non-insulin-dependent pathway (GLUT-4 translocation). This is particularly valuable for people with type 2 diabetes or prediabetes. The walk does not need to be intense — a brisk conversational pace is sufficient. Recommend a post-breakfast walk, post-lunch walk, and post-dinner walk for maximum glucose management benefit.',
 'Walking more than 90 minutes after the meal (the acute glucose spike has already occurred); performing high-intensity exercise immediately after eating (can cause GI distress); stopping the post-meal walk practice during rain or cold (an indoor walk or stair climbing works equally well).',
 'chronic_disease', array['30 minutes after eating: earlier is better — catch the glucose rise','10-15 minutes: short walks are highly effective for this purpose','Brisk: not slow — aim for a pace that slightly elevates breathing','Indoor alternatives: stair walking, indoor cycling, or even resistance exercise are effective'],
 array['Post-meal resistance training (equally effective)','Zone 2 cardio program','High-intensity interval training for HbA1c reduction'],
 array['Short slow walk after meals','Gentle seated leg movements after eating','Brief standing desk breaks after meals'],
 array['active_aging','type_2_diabetes','glucose_management','post_meal_walk','blood_sugar','lifestyle'], array['hypoglycaemia_risk_unmanaged'],
 'locomotion', 'sagittal', false, 1, null, 900, null, true),

('Cardiac Rehabilitation – Phase 2 Exercise Protocol',
 'cardiovascular', array['quadriceps','glutes'], array['cardiovascular','quadriceps'],
 'cardio', 'other', array['exercise_bike','treadmill'], 'beginner', false,
 'Phase 2 cardiac rehabilitation begins 2-6 weeks post-cardiac event (heart attack, cardiac surgery, or stent procedure). Supervised by a cardiologist or cardiac rehab team. Structure: (1) Warm-up 5 minutes — slow walking or light cycling. (2) Aerobic phase 20-40 minutes — moderate intensity (Borg Scale 11-13: "somewhat hard"; heart rate 60-70% of heart rate reserve). (3) Cool-down 10 minutes. (4) Resistance training 2 days/week: light weights (30-40% 1RM), 15-20 reps, avoiding the Valsalva manoeuvre. Exercise prescription is individualized based on the stress test result. NEVER exercise to maximal exertion.',
 'Exercising without medical clearance post-cardiac event; exercising alone without supervision in Phase 2 (must be supervised until cleared); using the Valsalva manoeuvre during resistance exercises (extreme blood pressure spike risk); exercising to maximum exertion (stop at "somewhat hard").',
 'chronic_disease', array['Medical supervision mandatory: this is a medical program, not a gym program','Borg 11-13: "somewhat hard" — the target intensity','No Valsalva: breathe continuously throughout every exercise','Warning signs: stop immediately with chest pain, dizziness, shortness of breath beyond expected, or palpitations'],
 array['Phase 3 cardiac rehab (community-based maintenance)','Return to recreational sport with cardiologist clearance','Home-based exercise with cardiac monitor'],
 array['Phase 1 (in-hospital) activity only','Supine gentle exercises only','Breathing exercises and early ambulation'],
 array['active_aging','cardiac_rehabilitation','heart_disease','post_mi','supervised','phase_2'], array['unstable_angina','recent_cardiac_event_under_2_weeks','uncontrolled_arrhythmia'],
 'mixed', 'multi', false, 1, null, 2400, null, true),

('Chronic Obstructive Pulmonary Disease – Exercise Program',
 'cardiovascular', array['core','shoulder'], array['cardiovascular','core'],
 'cardio', 'other', array['exercise_bike','resistance_band'], 'beginner', false,
 'COPD exercise training reduces breathlessness, hospitalisation risk, and improves quality of life. Pulmonary rehabilitation program structure: (1) Warm-up 5-10 minutes — gentle walking. (2) Cycling or walking: moderate intensity (Borg dyspnoea scale 3-4 — "moderate breathlessness"). (3) Duration: initially 10-20 minutes, building to 30-45 minutes. (4) Resistance training: light band exercises for upper and lower body — improves functional capacity. (5) Pursed-lip breathing: breathe in through the nose (2 counts), purse the lips and breathe out slowly (4 counts) — slows expiratory flow and reduces air trapping. (6) Frequency: minimum 3 days/week.',
 'Stopping exercise the moment any breathlessness begins (moderate breathlessness during exercise is expected and safe in COPD — it is the goal); not using pursed-lip breathing (this is one of the most effective dyspnoea management tools); exercising alone without an emergency plan in place.',
 'chronic_disease', array['Moderate breathlessness is expected: Borg 3-4 dyspnoea is the target, not avoidance','Pursed-lip breathing: exhale twice as long as the inhale — reduces air trapping','Start short: 10 minutes is appropriate initially — build gradually','Pulmonary rehab program: this should be delivered by a respiratory physiotherapist initially'],
 array['Pulmonary rehabilitation hospital program','Long-duration aerobic training as fitness improves','High-intensity interval training for advanced COPD patients (supervised)'],
 array['Seated breathing exercises only','Very short walks (2-5 minutes)','Energy conservation techniques and pacing education'],
 array['active_aging','copd','pulmonary_rehabilitation','breathlessness_management','chronic_disease'], array['acute_exacerbation_COPD','oxygen_saturation_under_88_at_rest'],
 'mixed', 'multi', false, 1, null, 1800, null, true),

-- ─── ZONE 2 CARDIO TRAINING ──────────────────────────────────────────────────
('Zone 2 Aerobic Training (Low-Intensity Steady State)',
 'cardiovascular', array['quadriceps','glutes'], array['cardiovascular','quadriceps'],
 'cardio', 'other', array['exercise_bike','treadmill'], 'intermediate', false,
 'Zone 2 training: continuous aerobic exercise at 60-70% of maximum heart rate (or roughly 65-75% of VO2 max). Clinical definition: the highest intensity where the body can clear lactate as fast as it is produced — staying below the first lactate threshold. How to gauge: the talk test — you should be able to speak in full sentences without gasping for air. Duration: 45-90 minutes per session. Frequency: 3-4 sessions per week. Benefits: mitochondrial biogenesis, fat oxidation efficiency, cardiovascular health, longevity markers, and aerobic base development. The most health-relevant form of cardio according to emerging longevity science.',
 'Going too hard and moving into Zone 3 (common — most people cannot stay in Zone 2 without monitoring their heart rate); thinking Zone 2 is "too easy" and rushing to harder training (the adaptation is cumulative and requires volume); doing Zone 2 for only 20-30 minutes (sub-45 minutes provides minimal Zone 2 adaptation).',
 'zone_2', array['Talk test: full sentences without gasping — this is Zone 2','45 minutes minimum: the adaptation requires duration, not intensity','Heart rate monitor: use one — perceived exertion overestimates Zone 2','Frequency: 3-4 sessions per week for 3-6 months to see measurable change'],
 array['Zone 2 intervals (4×30-minute blocks)','Zone 2 combined with Zone 5 (polarized training)','Long ride/run for endurance athletes (3-4 hours Zone 2)'],
 array['Walking at a comfortable pace (below Zone 2 for fit individuals)','Light cycling','Recreational swimming at easy effort'],
 array['zone_2','cardio','aerobic_base','mitochondria','fat_oxidation','longevity','steady_state'], array['unstable_cardiac_conditions'],
 'locomotion', 'sagittal', false, 1, null, 3600, null, true),

('Zone 2 Rowing Machine Protocol',
 'cardiovascular', array['back','quadriceps','core'], array['cardiovascular','back','quadriceps'],
 'cardio', 'other', array['rowing_machine'], 'beginner', false,
 'Rowing provides full-body Zone 2 training. Technique: (1) Catch — shins vertical, arms straight, lean forward slightly. (2) Drive — legs push first (80% of the power), then lean back, then pull with the arms. (3) Finish — legs extended, slight back lean (11 o''clock position), handle at the lower ribs. (4) Recovery — arms extend first, lean forward, knees bend. Zone 2 on the rower: comfortable effort, heart rate 60-70% max, full sentences possible. For a 45-minute session, expect roughly 8000-12000 metres depending on fitness level. Stroke rate: 18-22 strokes per minute for Zone 2.',
 'Pulling with the arms first (arm-dominant rowing — legs do most of the work); hunching the back on the catch (forward lean comes from the hip, not spinal flexion); going too hard and entering Zone 3-4 (monitor heart rate); too high a stroke rate for Zone 2 (slow the rate down to maintain the aerobic target).',
 'zone_2', array['Legs first: 80% of power from the legs — not the arms','Chain stays level: the handle path should be relatively horizontal','18-22 strokes/minute for Zone 2: slow and powerful, not fast and light','Heart rate target: 60-70% of max heart rate throughout'],
 array['Longer Zone 2 rows (60-90 minutes)','Rowing intervals for Zone 5 quality work','Rowing as part of polarized training plan'],
 array['Short 10-15 minute rows at low rate','Ergometer rowing 20 minutes','Cycling Zone 2 (less technical)'],
 array['zone_2','rowing','full_body_cardio','aerobic_base','technique','steady_state'], array['lower_back_pain_acute','shoulder_injury_acute'],
 'mixed', 'multi', false, 1, null, 2700, null, true),

-- ─── METABOLIC / EPOC CONDITIONING ───────────────────────────────────────────
('EPOC Training – Excess Post-Oxygen Consumption Protocol',
 'cardiovascular', array['quadriceps','glutes','core','chest'], array['cardiovascular','quadriceps'],
 'cardio', 'other', array['bodyweight','kettlebell','barbell'], 'advanced', false,
 'EPOC (excess post-exercise oxygen consumption) — the "afterburn effect" — is the elevated metabolic rate following high-intensity exercise. Maximised by: high-intensity intervals (>80% VO2 max), heavy resistance training, and metabolic conditioning. EPOC protocol: (1) Warm-up 10 minutes at moderate intensity. (2) EPOC block: 8-10 rounds of 30-second max-effort exercise / 30-second rest. Exercises: burpees, kettlebell swings, heavy barbell complexes, sprint intervals, or battle ropes. (3) Cool-down 10 minutes. EPOC effect: 100-200 additional kcal burned in the 24-48 hours post-exercise. Total workout: 30-40 minutes.',
 'Performing EPOC training daily (insufficient recovery — maximum 2-3 days per week); using EPOC as the only training modality (ignoring Zone 2 base which underpins EPOC adaptations); not warming up adequately before maximum intensity efforts.',
 'metabolic', array['Max effort: the 30 seconds must be true max effort — not moderate','Recovery matters: the 30-second rest is not optional — full recovery attempted','2-3 times per week: not daily — EPOC training requires recovery','Warm up properly: 10 minutes — cold muscles going to max effort is injury risk'],
 array['Tabata protocol (20 seconds on / 10 seconds off)','HIIT with longer efforts (40 seconds on / 20 seconds off)','Assault bike EPOC protocol (100% for 30 seconds)'],
 array['LISS cardio (Zone 2) as the base','Moderate-intensity interval training (70% effort)','Bodyweight circuit at 60-70% effort'],
 array['epoc','metabolic','afterburn','high_intensity','fat_loss','post_exercise_metabolism'], array['cardiovascular_disease','hypertension_uncontrolled','osteoporosis_severe'],
 'explosive', 'multi', false, 10, null, 30, 30, true),

('Metabolic Resistance Training (MRT) Circuit',
 'quadriceps', array['glutes','chest','back','shoulder','core'], array['quadriceps','glutes','chest'],
 'strength', 'strength', array['dumbbell','barbell','kettlebell'], 'intermediate', true,
 'Metabolic resistance training combines resistance exercises with minimal rest to create high metabolic demand. Circuit: (1) Dumbbell squat × 15; (2) Push-up × 15; (3) Dumbbell bent-over row × 15; (4) Dumbbell lunges × 12 per leg; (5) Dumbbell shoulder press × 12; (6) Plank 30 seconds; (7) Dumbbell deadlift × 12. No rest between exercises. Rest 90 seconds after each complete circuit. Complete 3-4 circuits. MRT trains strength, elevates heart rate to cardio zones, and creates significant EPOC. An efficient all-in-one session for people with limited time. Load: 15RM weight for each exercise.',
 'Using too heavy weight (form breaks down with no rest between exercises); resting between exercises (the metabolic effect requires continuous movement); skipping the 90-second circuit rest (fatigue accumulates — the rest between circuits is strategic, not optional).',
 'metabolic', array['15RM weight: if you could do 30 reps, the weight is too light','No rest between exercises: the circuit flows continuously','90 seconds between circuits: this is recovery, not optional rest','Form maintained: if form breaks, reduce the weight — not the rest'],
 array['Barbell complex MRT (same bar for all exercises)','MRT with kettlebell (swing, press, clean, squat complex)','Advanced MRT with 6 circuits and reduced rest'],
 array['Individual exercises with full rest','Circuit with longer rest periods','Bodyweight-only circuit for beginners'],
 array['metabolic','mrt','circuit','full_body','efficiency','epoc','time_efficient'], array['cardiovascular_disease_uncontrolled','orthopedic_limitations_multiple'],
 'mixed', 'multi', false, 4, 15, null, 90, true),

('Battle Rope HIIT (Upper Body Metabolic)',
 'shoulder', array['core','back','cardiovascular'], array['shoulder','core','cardiovascular'],
 'cardio', 'other', array['battle_ropes'], 'intermediate', false,
 'Anchor battle ropes to a fixed point. Grip one rope in each hand. Exercises and intervals: (1) Alternating waves — one arm goes up as the other goes down, 30 seconds. (2) Double waves — both arms up and down simultaneously, 20 seconds. (3) Lateral waves — waves moved from side to side, 20 seconds. (4) Slams — raise both ropes overhead and slam to the floor, 15 seconds. Rest 30-45 seconds between exercises. Repeat 3-4 rounds. Battle ropes provide intense upper-body cardiovascular conditioning, shoulder endurance, and core stability while being joint-friendly (low impact — no jumping).',
 'Standing too far from the anchor (ropes go slack — stand close enough that there is tension in the rope throughout the wave); tensing the neck and traps excessively (relax the shoulders and neck); performing waves from the wrists rather than the full arm and shoulder.',
 'metabolic', array['Close to the anchor: slack ropes mean no tension and no training effect','Full arm movement: the wave comes from the shoulder, not just the wrist','Slight squat stance: athletic base position, not standing upright rigidly','Lower body absorbs force: slight bend in the knees — do not lock out'],
 array['Longer battle rope intervals (45-60 seconds)','Battle rope with squat and press combination','Battle rope integrated into a full EPOC circuit'],
 array['Short 10-15 second intervals with long rest','Seated upper body resistance band exercises','Shoulder-specific resistance training'],
 array['metabolic','battle_ropes','hiit','upper_body','cardio','low_impact','shoulder_endurance'], array['shoulder_injury_acute','rotator_cuff_tear'],
 'mixed', 'multi', false, 4, null, 30, 45, true),

('Zone 5 Intervals (VO2 Max Training)',
 'cardiovascular', array['quadriceps','glutes'], array['cardiovascular','quadriceps'],
 'cardio', 'other', array['exercise_bike','treadmill'], 'advanced', false,
 'Zone 5 training targets VO2 max — the maximum oxygen uptake capacity. Protocol: 4-8 intervals of 3-5 minutes at 95-100% maximum heart rate. Rest: equal or double the work interval. Classic protocol (Tabata): 8 × 20 seconds at 170% VO2 max / 10 seconds rest. Classic protocol (Norwegian): 4 × 4 minutes at 90-95% max HR / 3 minutes rest. VO2 max is the strongest predictor of all-cause mortality — improving it by even 1 MET reduces cardiovascular mortality risk by approximately 13%. Zone 5 should comprise approximately 10-20% of weekly training volume in a polarized model.',
 'Doing Zone 5 work without Zone 2 base (Zone 5 adaptations are limited without adequate aerobic base); performing Zone 5 work more than 2-3 times per week (excessive high-intensity training increases injury and burnout risk); not recovering fully between intervals (Zone 5 requires true maximal efforts — partial recovery means partial effort).',
 'zone_5', array['True max effort: 95-100% is genuinely all-out — uncomfortable','Full recovery: 3-4 minutes rest between intervals for quality repetition','2x per week maximum: more high-intensity reduces adaptation quality','Aerobic base first: 3-6 months of Zone 2 training underpins Zone 5 gains'],
 array['4×4 Norwegian interval training','Staircase VO2 max progression protocol','Polarized training plan integrating Zone 2 and Zone 5'],
 array['Zone 2 aerobic training (must master this first)','Tempo run (Zone 3 — threshold training)','Moderate-intensity intervals (Zone 3-4)'],
 array['zone_5','vo2max','intervals','cardiovascular','longevity','polarized','high_intensity'], array['cardiovascular_disease','hypertension_uncontrolled','osteoporosis_severe'],
 'explosive', 'sagittal', false, 6, null, 240, 180, true);

-- ─── ACTIVE AGING – STRENGTH & SARCOPENIA PREVENTION ─────────────────────────
insert into exercises (name, primary_muscle_group, secondary_muscle_groups, muscle_groups, category, movement_type, equipment, difficulty_level, is_compound, instructions, common_mistakes, subcategory, coaching_cues, progressions, regressions, tags, contraindications, force_type, plane_of_motion, is_unilateral, sets_default, reps_default, duration_seconds, rest_seconds, is_system) values

('Resistance Band Full Body – Seniors Program',
 'quadriceps', array['glutes','back','shoulder','core'], array['quadriceps','glutes','back'],
 'strength', 'strength', array['resistance_band'], 'beginner', false,
 'Resistance bands are ideal for seniors: inexpensive, joint-friendly, variable resistance, and usable at home. Complete program (3 days/week): (1) Squat with band under feet (hold handles at shoulder height — goblet squat position), 3×15. (2) Band row seated on floor or chair, 3×15. (3) Standing band shoulder press, 3×12. (4) Band hip hinge (deadlift pattern), 3×15. (5) Band bicep curl, 3×15. (6) Band overhead tricep extension, 3×12. (7) Standing band side step (lateral walk), 3×15 steps each direction. Progress: increase band resistance colour every 4-6 weeks when 15 reps feel easy.',
 'Using a band that is too light (any exercise should be challenging by rep 12-15; too light means no muscle-building stimulus); not progressing the band resistance over time (progressive overload is required even with bands); anchoring the band insecurely (safety risk if the band snaps or the anchor fails).',
 'active_aging', array['Challenge by rep 12-15: if the last 3 reps are not hard, the band is too light','Progress every 4-6 weeks: increase band colour/resistance when the program becomes easy','Anchor safely: under the foot or to a fixed door anchor — test before loading','3 days per week: the minimum effective dose for muscle strength maintenance'],
 array['Add dumbbells to replace band exercises as strength improves','Machine-based strength training program','Full gym program with barbell and dumbbell'],
 array['Single exercises with very light band','Seated band exercises only','Chair-based strength circuit'],
 array['active_aging','resistance_band','seniors','full_body','sarcopenia_prevention','home_training'], array[],
 'mixed', 'multi', false, 3, 15, null, 60, true),

('Heel Raise Calf Strength (Peripheral Circulation)',
 'calves', array['ankle_stabilisers'], array['calves'],
 'strength', 'strength', array['bodyweight','step'], 'beginner', false,
 'Stand behind a sturdy chair for support. Feet hip-width. Rise onto the toes (plantarflex to maximum height). Hold 2 seconds. Lower slowly. Progress: single-leg heel raises. Beyond muscle strength, calf raises stimulate the muscle pump mechanism — the calf muscles compress the deep veins on each contraction, pushing venous blood back toward the heart against gravity. This is particularly important for older adults with impaired venous return, deep vein thrombosis risk, or peripheral oedema. Calf strength also significantly reduces fall risk by improving ankle reactive balance.',
 'Not reaching full plantarflexion (partial range means partial stimulus); bouncing up without control; on a step only: not going below horizontal on the descent (partial range eliminates the stretch and eccentric component).',
 'active_aging', array['Maximum height: rise as high as possible — do not do half rises','2-second hold: the pause reinforces the neuromuscular contraction','Slow descent: 3 counts down — the eccentric is where strength is built','Venous pump: even seated calf raises help — practise during TV watching'],
 array['Single-leg calf raise on step (full range)','Weighted calf raise (holding dumbbell)','Jump rope calf conditioning (much later)'],
 array['Seated calf raise in chair','Ankle circles for mobility','Foot tapping seated exercise'],
 array['active_aging','calf_strength','venous_pump','circulation','fall_prevention','peripheral_health'], array['deep_vein_thrombosis_active','achilles_tendinopathy'],
 'push', 'sagittal', false, 3, 20, null, 45, true),

('Progressive Walking Program (10,000 Steps Protocol)',
 'cardiovascular', array['quadriceps','glutes'], array['cardiovascular','quadriceps'],
 'cardio', 'other', array['bodyweight'], 'beginner', false,
 'Walking is the most evidence-supported exercise for older adults and chronic disease prevention. Progressive walking protocol: Week 1-2: baseline step count (wear a pedometer or use a phone — measure your average daily steps without trying). Week 3-4: add 1000 steps per day above baseline. Week 5-8: add another 1000 steps/day (total +2000). Continue adding 500-1000 steps per week until reaching 7000-10000 steps/day. Each 1000-step increase beyond a sedentary baseline is associated with approximately 6-8% mortality risk reduction. Target: 7000-10000 steps for optimal health outcomes.',
 'Starting at 10000 steps immediately from a sedentary baseline (musculoskeletal overuse injury risk); not tracking steps (the pedometer/phone is essential for progressive overload); focusing only on total steps rather than including some faster-paced walking for cardiovascular stimulus.',
 'active_aging', array['Measure first: know your baseline before adding steps','+1000 per week: gradual progression avoids overuse injury','Include faster walking: some brisk walking within the daily steps for cardiovascular benefit','7000 is the key: research shows large benefits begin at 7000 steps — 10000 is a ceiling, not mandatory'],
 array['Walking with poles (Nordic walking for upper body)','Walk-jog intervals as fitness improves','Hiking with vertical elevation gain'],
 array['Short indoor walks','Seated marching at home','10-minute walk once daily'],
 array['active_aging','walking','steps','longevity','chronic_disease_prevention','all_ages'], array['peripheral_vascular_disease_severe'],
 'locomotion', 'sagittal', false, 1, null, 1800, null, true),

('Grip Strength Training (Longevity Marker)',
 'forearms', array['biceps','shoulder'], array['forearms','biceps'],
 'strength', 'strength', array['grip_trainer','barbell'], 'beginner', false,
 'Grip strength is one of the strongest independent predictors of all-cause mortality, cardiovascular disease, and functional independence. For every 5 kg reduction in grip strength, cardiovascular mortality risk increases by 17% (Lancet, 2015). Exercises: (1) Dead hang from a pull-up bar — 3×20-30 seconds; (2) Farmer''s carry — carry heavy dumbbells 30 metres, rest, repeat 3 times; (3) Hand gripper squeeze — 3×20; (4) Barbell holds — hold a loaded barbell without any curling or pulling, just grip — 3×30 seconds; (5) Towel pull-up — drape a towel over a bar and grip the towel ends — 3×10-15 seconds hang. Grip training improves with any loaded exercise where the bar is held.',
 'Neglecting grip training as a secondary concern (grip strength is a primary health marker — not an afterthought); using straps for all exercises (straps reduce grip training stimulus); not testing grip strength periodically with a hand dynamometer.',
 'active_aging', array['Grip is a health marker: test it with a dynamometer annually','No straps for most exercises: let the grip be trained in all exercises','Farmer''s carry is simplest: pick up something heavy and walk','Improve over time: grip strength improving year to year is the goal — it indicates maintained muscle and neural health'],
 array['Towel pull-ups (extreme grip demand)','Dead hang with added weight (dip belt)','Axle bar (fat bar) training for grip'],
 array['Hand gripper at home (low resistance)','Wrist roller exercises','Rubber band finger extensions'],
 array['active_aging','grip_strength','longevity','mortality_predictor','farmer_carry','functional_strength'], array['carpal_tunnel_syndrome','wrist_injury_acute'],
 'pull', 'sagittal', false, 3, null, 30, 60, true),

('Osteoporosis – Safe Bone Loading Protocol',
 'quadriceps', array['glutes','back','core'], array['quadriceps','glutes','back'],
 'strength', 'strength', array['dumbbell','resistance_band','step'], 'intermediate', false,
 'Osteoporosis requires specific exercise types to stimulate bone formation: (1) Weight-bearing exercises (walking, jogging if appropriate, hiking, dancing) — gravity loading stimulates bone. (2) Impact exercises (if not fracture-risk): step-ups, gentle hopping, stair climbing — impact forces stimulate osteoblast activity. (3) Resistance training (most critical): squats, deadlifts, rows, press variations — loaded exercises provide the greatest bone-building stimulus. Spine flexion under load is CONTRAINDICATED (no crunches, sit-ups, or heavy loaded forward bending — fracture risk for vertebral compression). Exercise intensity should be moderate-to-high for bone adaptation.',
 'Spine flexion under load (sit-ups, crunches, heavy deadlifts with rounding — vertebral fracture risk in osteoporosis); avoiding all exercise due to fracture fear (exercise is the primary prevention of further bone loss and fracture risk); selecting only gentle stretching without loading (insufficient mechanical stimulus for bone adaptation).',
 'active_aging', array['Load the bones: weight-bearing and resistance exercise is essential — not optional','NO spinal flexion under load: this means no crunches, no situps, no deadlift rounding','Impact is beneficial: hopping, jumping rope, and step-ups are bone builders','Density takes 12-18 months: be patient — bone adaptation is slow'],
 array['Weighted vest walking (adds impact loading)','Olympic lifting variations (if medically cleared — extreme bone loading)','High-load resistance training for maximal bone stimulus'],
 array['Walking only (weight-bearing without impact)','Resistance band exercises without heavy loading','Swimming or cycling (limited bone benefit but maintain cardiovascular health)'],
 array['active_aging','osteoporosis','bone_health','bone_loading','fracture_prevention','spine_safety'], array['vertebral_compression_fracture_recent','severe_osteoporosis_T_score_under_3'],
 'mixed', 'multi', false, 3, 12, null, 90, true),

('Flexibility & Mobility Program for Seniors (Daily)',
 'core', array['hip_flexors','hamstrings','shoulder','back'], array['core'],
 'mobility', 'flexibility', array['bodyweight','yoga_mat'], 'beginner', false,
 'A 15-20 minute daily flexibility routine for healthy aging. Sequence: (1) Seated hip flexor stretch — sit at the edge of a chair, one leg dangling (passive hip extension), 30 seconds each side. (2) Standing calf stretch against wall, 30 seconds each. (3) Doorway chest/shoulder stretch, 30 seconds. (4) Seated hamstring stretch — one leg extended on another chair, lean forward gently, 30 seconds each. (5) Supine knee-to-chest stretch, 30 seconds each. (6) Seated thoracic rotation, 10 reps each way. (7) Neck chin tuck and lateral flexion, 10 reps each. Total time: 15-20 minutes. Reduces fall risk, reduces back pain, and maintains functional independence.',
 'Bouncing in the stretch (ballistic stretching increases injury risk in older adults — hold static); stretching to the point of pain (should feel gentle tension, not pain); doing this once per week (daily practice required for flexibility changes in older adults — the body adapts more slowly).',
 'active_aging', array['Static holds: 30 seconds each — no bouncing in older adults','Tension, not pain: feel a gentle pull, not sharp pain or discomfort','Daily practice: flexibility in older adults requires daily work to maintain and improve','Morning routine: attach this to the morning routine for adherence'],
 array['Yoga class (adapted for seniors)','Pilates flexibility program','Full body dynamic warm-up (more advanced)'],
 array['Single stretch focus per day','Chair-based stretching only','Passive assistance with gentle partner stretching'],
 array['active_aging','flexibility','mobility','daily_routine','seniors','functional_independence','pain_prevention'], array[],
 'isometric', 'multi', false, 1, null, 1200, null, true);

-- ─── COGNITIVE HEALTH & DUAL-TASK TRAINING ───────────────────────────────────
insert into exercises (name, primary_muscle_group, secondary_muscle_groups, muscle_groups, category, movement_type, equipment, difficulty_level, is_compound, instructions, common_mistakes, subcategory, coaching_cues, progressions, regressions, tags, contraindications, force_type, plane_of_motion, is_unilateral, sets_default, reps_default, duration_seconds, rest_seconds, is_system) values

('Dual-Task Walking (Cognitive + Physical)',
 'cardiovascular', array['core','quadriceps'], array['cardiovascular','core'],
 'functional', 'other', array['bodyweight'], 'intermediate', false,
 'Dual-task training combines a physical movement with a simultaneous cognitive task. This replicates real-world scenarios where falls occur — distracted walking. Protocols: (1) Walk and count backwards from 100 by 3s; (2) Walk and name animals alternating A-Z (Ant, Bear, Cat...); (3) Walk and sort a deck of cards into colours; (4) Walk while reciting months of the year backwards. The goal: maintain walking speed and gait quality while performing the cognitive task. Dual-task training reduces fall incidence in older adults by approximately 30-40%. Used extensively in dementia prevention research.',
 'Slowing to a complete stop when the cognitive task becomes difficult (this is the deficit we are training to overcome — push through); choosing cognitive tasks that are too easy (the cognitive component must genuinely challenge the individual); performing only on flat indoor surfaces (progress to outdoor terrain and real-world distraction environments).',
 'active_aging', array['Do not stop walking: the cognitive task should not pause the gait','Challenge: if it feels easy, use a harder cognitive task','Outdoor progression: take dual-task training outside — real-world distractions are the target','Safety: have a partner walk alongside initially for safety'],
 array['Dual-task balance challenges (standing on foam while counting)','Dual-task stair climbing','Dual-task strength training (counting reps while doing complex movements)'],
 array['Simple counting while seated','Single-task walking at normal pace','Cognitive exercises only (seated)'],
 array['active_aging','dual_task','cognitive','fall_prevention','dementia_prevention','brain_health'], array['severe_cognitive_impairment','acute_vestibular_disorder'],
 'locomotion', 'sagittal', false, 3, null, 300, 60, true),

('Balance Board & Proprioception Training',
 'core', array['ankle_stabilisers','quadriceps','glutes'], array['core','quadriceps'],
 'functional', 'other', array['balance_board','bosu'], 'intermediate', false,
 'Proprioceptive training on unstable surfaces. Progression: (1) Two-leg stance on a folded mat (easy instability) — 3×30 seconds; (2) BOSU dome side up, two-leg stance — 3×30 seconds; (3) BOSU dome side up, single-leg — 3×20 seconds; (4) Balance board two-leg — 3×30 seconds; (5) Balance board with ball toss to a wall — 3×30 seconds; (6) Balance board single-leg — 3×20 seconds. The ankle, knee, and hip must all make micro-adjustments on unstable surfaces, training the proprioceptive system (the body''s position-sense system) — critical for reactive balance when stepping on unexpected surfaces.',
 'Starting on extremely unstable surfaces without progressive build-up (fall risk); not having a partner or sturdy support nearby; using unstable surfaces for all exercises (stable + unstable surface alternation is optimal for strength and proprioception both).',
 'active_aging', array['Progression order: flat mat → BOSU → balance board','Safety first: a partner or support within reach for the harder progressions','Eyes closed to increase difficulty: removing vision is the biggest challenge','Proprioception ages fast: use it or lose it — train it consistently'],
 array['Slackline walking (extreme proprioception)','Single-leg balance board with sport-specific movements','Perturbation training (partner pushes the surface unexpectedly)'],
 array['Single-leg stand on flat ground (no equipment)','Tandem stand (heel-to-toe) on flat ground','Eyes-open single-leg stand on floor'],
 array['active_aging','proprioception','balance_board','bosu','ankle_stability','fall_prevention'], array['acute_ankle_sprain','severe_vestibular_disorder'],
 'isometric', 'multi', false, 3, null, 30, 30, true),

('Group Exercise Class – Social Movement for Seniors',
 'cardiovascular', array['core','shoulder','quadriceps'], array['cardiovascular','core'],
 'cardio', 'other', array['bodyweight','chair'], 'beginner', false,
 'Group exercise for older adults provides physical AND social health benefits. Evidence: social isolation in older adults doubles the risk of dementia and depression, and increases all-cause mortality risk by 26%. Group exercise programs: (1) Chair aerobics — seated movement to music; (2) Dance fitness adapted for older adults (Silver Sneakers, EnhanceFitness); (3) Tai Chi (strong fall prevention evidence — Cochrane review: 23% fall reduction); (4) Bowling, bocce ball, golf; (5) Walking groups. The joy and social connection of group exercise dramatically improves adherence. Even low-intensity group exercise outperforms high-intensity solo exercise for total health outcomes when the social component is included.',
 'Prioritising solo high-intensity exercise over group exercise when social connection is absent (the loneliness epidemic in older adults makes social exercise superior for total health); pushing the group pace beyond comfort for less-fit participants.',
 'active_aging', array['Bring a friend: even better with a companion — the social element doubles the benefit','Community programs: local council, community health centres, and Silver Sneakers offer these programs','Regularity over intensity: showing up every week to a gentle group class outperforms sporadic intense solo training','Tai Chi: evidence-based fall prevention that is also social and enjoyable'],
 array['Competitive recreational sport (lawn bowls, golf, tennis)','Volunteering with physical activity component','Intergenerational exercise programs'],
 array['One-on-one physiotherapy-led exercise','Online group exercise class (less social but still group)','Walking with one friend'],
 array['active_aging','social_exercise','group_class','fall_prevention','mental_health','dementia_prevention','loneliness'], array[],
 'mixed', 'multi', false, 1, null, 3600, null, true),

('Tai Chi – Fall Prevention Sequence',
 'core', array['quadriceps','hip_stabilisers','shoulder'], array['core','quadriceps'],
 'functional', 'other', array['bodyweight'], 'beginner', false,
 'Tai Chi is one of the most evidence-supported fall prevention interventions (Cochrane systematic review: 23% relative risk reduction in falls). Basic sequence for beginners: (1) Opening form — feet shoulder-width, arms raise slowly forward to shoulder height, palms down; lower to sides. (2) Ward off — shift weight to one leg, raise opposite arm in a curved push motion. (3) Single whip — open arms wide to the sides, one hand hooks. (4) Cloud hands — hands trace horizontal circles in front of the body as weight shifts side to side. (5) Closing form — arms slowly lower. Each movement is performed slowly, continuously, with focused breath. Practice 20-30 minutes daily.',
 'Rushing the movements (Tai Chi is defined by its slow speed — rushing eliminates the balance-training component); holding the breath (Tai Chi integrates breath throughout); copying movements without understanding the weight-shifting (the lateral weight transfer is the primary balance-training mechanism).',
 'active_aging', array['Slow is the point: movements are performed in slow motion deliberately','Weight shift: every movement transfers weight from one leg to the other — this trains balance','Breathe: in through the nose on the "receiving" movement, out through the nose on the "giving" movement','Daily practice: 30 minutes daily gives the significant fall-prevention benefit'],
 array['Full Yang-style Tai Chi 24-form','Advanced 108-form traditional Tai Chi','Tai Chi sword form for upper body integration'],
 array['Seated Tai Chi (chair-based upper body only)','Simple bilateral arm movements in standing','Standing balance practice'],
 array['active_aging','tai_chi','fall_prevention','balance','mind_body','seniors','evidence_based'], array['acute_vestibular_disorder'],
 'isometric', 'multi', false, 1, null, 1800, null, true),

('Strength for Longevity – Compound Lift Program (60+)',
 'quadriceps', array['glutes','back','chest','shoulder','core'], array['quadriceps','glutes','back'],
 'strength', 'strength', array['barbell','dumbbell','cable_machine'], 'intermediate', true,
 'Resistance training over 60 should prioritise compound movements with appropriate loading. Evidence: resistance training 2-3 days/week reduces all-cause mortality risk by 20-23% independently of aerobic exercise. Program: 3 days/week (Monday/Wednesday/Friday or similar): (A) Squat pattern (goblet squat or leg press) 3×10-12; (B) Hip hinge (Romanian deadlift or trap bar deadlift) 3×10; (C) Horizontal push (dumbbell press or machine press) 3×10-12; (D) Horizontal pull (seated cable row or machine row) 3×10-12; (E) Single-leg exercise (step-up or split squat) 2×10 each. Load: the final 2 reps of each set should be challenging. Progress monthly. This program maintains muscle mass, bone density, metabolic rate, and functional independence.',
 'Avoiding resistance training due to age-related fear of injury (strength training is safe and essential for healthy aging — injury risk is LOW with appropriate loading and technique); using loads that are too light to stimulate muscle protein synthesis (must be challenging by the last few reps); training every day without recovery time (2-3 days per week with rest between is optimal).',
 'active_aging', array['Challenge is required: if the last 3 reps are easy, add weight','2-3 days per week: strength adaptations require recovery days between sessions','Compound movements: squats, rows, presses, and hip hinges are the most functional movements for independence','Progressive: increase weight monthly — strength adapts to the load placed upon it'],
 array['Powerlifting for masters athletes (age 60+)','Olympic weightlifting for masters (many masters Olympic lifters)','Progressive overload periodised program'],
 array['Resistance band full body program','Chair-based strength exercises','Single exercise focus per session'],
 array['active_aging','strength_training','longevity','compound_lifts','sarcopenia_prevention','mortality_reduction'], array[],
 'mixed', 'multi', false, 3, 12, null, 90, true);
