-- Exercise seed data — Batch 8
-- Pregnancy & Postnatal Fitness
-- Prenatal safe exercises by trimester, postnatal recovery, diastasis recti rehabilitation, pelvic floor

insert into exercises (name, primary_muscle_group, secondary_muscle_groups, muscle_groups, category, movement_type, equipment, difficulty_level, is_compound, instructions, common_mistakes, subcategory, coaching_cues, progressions, regressions, tags, contraindications, force_type, plane_of_motion, is_unilateral, sets_default, reps_default, duration_seconds, rest_seconds, is_system) values

-- ─── PELVIC FLOOR FOUNDATIONS ─────────────────────────────────────────────────
('Kegel Exercise (Pelvic Floor Contraction)',
 'core', array[], array['core'],
 'rehab', 'other', array['bodyweight'], 'beginner', false,
 'Identify the pelvic floor muscles: the muscles used to stop the flow of urine. Squeeze these muscles and hold for 3-5 seconds (beginners), building to 10 seconds over weeks. Relax completely for an equal duration. Perform 10 repetitions per set. Can be done in any position — seated, standing, lying. Breathing continues normally throughout. The pelvic floor supports the bladder, bowel, and uterus. Kegels prevent and treat stress urinary incontinence, improve sexual function, and support postnatal recovery. Both men and women benefit from pelvic floor training.',
 'Holding the breath (should breathe normally throughout); contracting the gluteal or adductor muscles instead of the pelvic floor (the pelvic floor contraction should be internal and upward); over-training kegels without relaxation (hypertonic pelvic floor also causes dysfunction — rest is needed); not finding the correct muscles.',
 'prenatal', array['Internal lift: imagine lifting a marble up into the body','Equal rest: relax as long as you contract — both matter','Breathe through: do not hold the breath','Find the muscles first: if you are not sure you are contracting correctly, see a pelvic floor physiotherapist'],
 array['Extended Kegel holds (10-second holds)','Kegel during functional movements (walking, squatting)','Pelvic floor physiotherapy for advanced assessment'],
 array['Diaphragmatic breathing awareness only','Manual physiotherapy assessment and guidance','Supine position Kegel to remove gravity initially'],
 array['prenatal','postnatal','pelvic_floor','kegel','incontinence','core','women'], array['pelvic_floor_hypertonia'],
 'isometric', 'sagittal', false, 3, 10, null, 60, true),

('Pelvic Floor Bulge & Lift Drill',
 'core', array[], array['core'],
 'rehab', 'other', array['bodyweight'], 'intermediate', false,
 'Lie on the back with knees bent. Breathe in deeply (diaphragmatic breath) — as you inhale, consciously RELAX and allow the pelvic floor to gently descend or bulge downward. On the exhale, lift the pelvic floor upward and inward. This is the 360° breathing and pelvic floor coordination pattern. Critical for diastasis recti management. The exhale-lift coordination helps manage intra-abdominal pressure and is the foundation of all postnatal core exercises. Must be mastered before any loaded movement.',
 'Activating the pelvic floor on the inhale (should relax on inhale, lift on exhale); using the gluteal or adductor muscles instead of an isolated pelvic floor lift; skipping this foundational drill and progressing to advanced exercises too early.',
 'prenatal', array['Inhale = relax and let go: the pelvic floor descends','Exhale = lift up and in: coordinated with the breath','360° breathing: ribs expand in all directions on the inhale','Foundation: nothing loaded until this is automatic'],
 array['Pelvic floor activation during sitting to standing','Kegel combined with 360° breathing','Functional pelvic floor integration with walking'],
 array['Basic Kegel exercise','Supine diaphragmatic breathing only','Pelvic floor physiotherapy assessment'],
 array['prenatal','postnatal','pelvic_floor','breathing','coordination','diastasis_recti'], array['pelvic_floor_hypertonia'],
 'isometric', 'sagittal', false, 3, 10, null, 60, true),

-- ─── FIRST TRIMESTER (WEEKS 1–12) ─────────────────────────────────────────────
('Prenatal Walk (First Trimester)',
 'cardiovascular', array['quadriceps','glutes'], array['cardiovascular','quadriceps'],
 'cardio', 'other', array['bodyweight'], 'beginner', false,
 'Walking is safe throughout pregnancy when not contraindicated. First trimester: fatigue and nausea may limit intensity. Aim for 20-30 minutes of moderate-intensity walking most days. Moderate intensity: able to hold a conversation but slightly elevated heart rate. Avoid overheating (stay below 38°C core temperature). Hydrate before, during, and after. Wear supportive footwear — centre of gravity shifts during pregnancy. Walking maintains cardiovascular fitness, reduces gestational diabetes risk, improves mood, and manages weight gain.',
 'Walking in extreme heat (overheating risk); not hydrating adequately; wearing unsupportive footwear; continuing if experiencing dizziness, chest pain, vaginal bleeding, or contractions (stop immediately and seek medical attention).',
 'prenatal', array['Conversational pace: can you talk? Good intensity','Hydrate: water before, during, and after','Stop signs: bleeding, dizziness, contractions, chest pain — stop and call your doctor','Footwear: supportive running shoes as the belly grows and balance shifts'],
 array['Prenatal light jog (if pre-pregnancy runner and medically cleared)','Nordic walking with poles for upper body','Prenatal hike on gentle terrain'],
 array['Seated chair marching (if very fatigued or at risk)','Aqua walking in the pool','Short 10-minute walks building to 30 minutes'],
 array['prenatal','first_trimester','walking','cardio','safe_exercise','low_impact'], array['placenta_previa','preterm_labour_risk','hypertension_pregnancy'],
 'locomotion', 'sagittal', false, 1, null, 1800, null, true),

('Prenatal Bodyweight Squat',
 'quadriceps', array['glutes','hamstrings','core'], array['quadriceps','glutes'],
 'strength', 'strength', array['bodyweight'], 'beginner', true,
 'Feet slightly wider than hip-width, toes turned out 15-30° to accommodate the growing belly. Lower as if sitting into a chair — weight through the heels, knees tracking over the toes. Do not go below a comfortable range — pregnancy ligament laxity makes deep squat caution appropriate. Exhale on the way up, coordinating with a gentle pelvic floor lift. Squats maintain leg and glute strength, improve posture (counteracting the anterior pelvic tilt of pregnancy), and prepare the body for labour positions. Stop if pelvic pressure is uncomfortable.',
 'Knees caving inward; excessive forward lean (more than 45°); going deeper than comfortable — do not force range of movement; not breathing (holding breath increases intra-abdominal pressure and stresses the pelvic floor).',
 'prenatal', array['Wide stance: to make room for the belly as it grows','Exhale up: coordinate the breath with the pelvic floor lift','Track knees over toes: add a band above the knees if needed','Comfortable range: pregnancy is not the time to improve depth — move within comfort'],
 array['Goblet squat with light weight','Sumo squat for easier belly clearance','Wall squat with stability ball support'],
 array['Supported squat with TRX or rings','Chair squat (sit to chair and stand)','Wall sit isometric'],
 array['prenatal','first_trimester','squat','leg_strength','functional','labour_preparation'], array['placenta_previa','symphysis_pubis_dysfunction'],
 'push', 'sagittal', false, 3, 15, null, 60, true),

('Seated Prenatal Upper Body Strength',
 'shoulder', array['chest','triceps','back'], array['shoulder','chest','back'],
 'strength', 'strength', array['dumbbell','resistance_band'], 'beginner', false,
 'Seated in a sturdy chair. Perform upper body exercises while seated to reduce balance demands as the belly grows. Exercises: (1) Seated dumbbell shoulder press 3×12; (2) Seated dumbbell bicep curl 3×12; (3) Seated resistance band row 3×12; (4) Seated resistance band chest press 3×12. Rest 60 seconds between sets. Breathe consistently — exhale on the exertion phase. Maintaining upper body strength during pregnancy reduces back pain and helps prepare for the physical demands of carrying and caring for a newborn.',
 'Lying on the back after the first trimester (avoid from 16+ weeks — can compress the vena cava); pressing overhead when the baby drops and puts pressure on the pelvic floor (switch to lateral raises); using heavy weights that require breath-holding.',
 'prenatal', array['Seated for safety: balance is reduced during pregnancy','Exhale on effort: consistent breathing throughout','Upper body prep: carrying a baby requires upper body strength','Moderate weight: 12-15 reps should be challenging but not exhausting'],
 array['Add more upper body exercises as strength improves','Resistance band full upper body circuit','Prenatal group class upper body component'],
 array['Light resistance band exercises only','Manual resistance exercises','Posture exercises and stretching only'],
 array['prenatal','upper_body','seated','safe_pregnancy','strength','newborn_prep'], array['preeclampsia','bed_rest_ordered'],
 'push', 'sagittal', false, 3, 12, null, 60, true),

('Cat-Cow Prenatal Mobilisation',
 'back', array['core','hip_flexors'], array['back','core'],
 'mobility', 'flexibility', array['bodyweight'], 'beginner', false,
 'Hands and knees position (quadruped). Hands under shoulders, knees under hips. On the inhale, allow the belly to drop toward the floor, lift the head and tailbone (cow pose — lumbar extension). On the exhale, round the entire spine, draw the belly up toward the spine gently (without crunching — this is a gentle lift not a crunch), and drop the head (cat pose — spinal flexion). This mobilises the thoracic and lumbar spine, relieves back pain, and encourages pelvic floor coordination with breath. Particularly relieving in the third trimester when back pain peaks.',
 'Forcing extreme range in either direction; dropping the wrists under excessive belly weight (use a wrist cushion or fist position); holding the breath; performing with any wrist, knee, or hip pain.',
 'prenatal', array['Gentle movement: this is mobilisation, not yoga extremes','Breathe with the movement: inhale to cow, exhale to cat','Belly gently lifts in cat: do not crunch — a gentle lift','Relieve back pain: this is one of the best pregnancy back pain exercises'],
 array['Thread the needle (thoracic rotation from quadruped)','Bird-dog from quadruped (postnatal progression)','Extended range thoracic mobilisation'],
 array['Seated spinal flexion and extension','Standing lumbar mobilisation','Supported knee-to-chest stretch'],
 array['prenatal','all_trimesters','back_pain_relief','spinal_mobility','quadruped','cat_cow'], array['wrist_injury','knee_injury'],
 'mixed', 'sagittal', false, 3, 10, null, 30, true),

-- ─── SECOND TRIMESTER (WEEKS 13–26) ──────────────────────────────────────────
('Prenatal Side-Lying Hip Abduction',
 'glutes', array['hip_abductors'], array['glutes'],
 'strength', 'strength', array['bodyweight','resistance_band'], 'beginner', false,
 'Lie on one side with a pillow supporting the head and potentially a pillow between the knees for hip alignment. Bottom leg straight or slightly bent. Top leg raises in an arc (hip abduction) to about 45°. Hold briefly, lower with control. Can add a resistance band above the knees for more resistance. This exercise strengthens the gluteus medius, which weakens during pregnancy contributing to pelvic girdle pain and the Trendelenburg gait pattern seen in many pregnant women. Side-lying is safe throughout pregnancy (avoids supine position).',
 'Internal rotation of the top hip (rotating the knee toward the floor — should maintain neutral rotation with the toe pointing forward); raising too high and using the lumbar spine to compensate; not maintaining a neutral pelvis (pelvis should not tilt).',
 'prenatal', array['Neutral hip: toes point forward — do not rotate internally','Pelvis stable: does not tilt backward as the leg raises','45° maximum: hip abduction, not a full lateral leg raise to the sky','Side-lying is safe: avoids pressure on the vena cava from second trimester on'],
 array['Clamshell exercise (banded)','Side-lying hip abduction with added band resistance','Side-lying hip abduction and adduction combined'],
 array['Supine leg lift (first trimester only)','Standing hip abduction with support','Seated hip abduction with resistance band'],
 array['prenatal','second_trimester','glute_medius','side_lying','pelvic_girdle','hip_abduction'], array['symphysis_pubis_dysfunction','pelvic_girdle_pain_severe'],
 'push', 'frontal', true, 3, 15, null, 60, true),

('Prenatal Clamshell with Band',
 'glutes', array['hip_abductors'], array['glutes'],
 'strength', 'strength', array['resistance_band'], 'beginner', false,
 'Lie on one side with hips stacked and knees bent at approximately 45-90°. Place a light resistance band above the knees. Open the top knee like a clamshell, keeping the feet together. The pelvis must remain completely still — no rotation backward. Open as far as possible without pelvis rotation, hold 2 seconds, lower. The clamshell targets the gluteus medius in external rotation — critical for pelvic stability, reducing hip and low back pain during pregnancy. Often prescribed by physiotherapists for pelvic girdle pain management.',
 'Pelvis rotating backward as the knee rises (the most common error — place a hand on the pelvis to monitor); not keeping the feet together (they should stay stacked); using too strong a band (range is lost).',
 'prenatal', array['Pelvis does not move: if it rotates, the range is too large','Feet together always: the rotation comes from the hip, not the feet','2-second hold at the top: feel the glute medius contracting','Light band first: resistance can increase when form is perfect'],
 array['Clamshell with heavier band','Clamshell with hip extension (add a kick at the top)','Standing glute medius exercises progressed from clamshell'],
 array['Clamshell without band (bodyweight only)','Supine glute bridge (earlier stage)','Side-lying hip abduction (similar muscle group)'],
 array['prenatal','second_trimester','clamshell','glute_medius','pelvic_stability','band'], array['symphysis_pubis_dysfunction','pelvic_girdle_pain_severe'],
 'push', 'frontal', true, 3, 15, null, 60, true),

('Prenatal Wall Push-Up',
 'chest', array['triceps','shoulder'], array['chest','triceps'],
 'strength', 'strength', array['bodyweight'], 'beginner', false,
 'Stand facing a wall, arms extended, hands at shoulder height and slightly wider than shoulder-width. Feet 60-90 cm from the wall. Bend the elbows, lowering the chest toward the wall. Press back to start. Breathing: exhale on the push. This is the safest push-up progression during pregnancy as the belly is accommodated and there is no compression on the abdomen. Maintains chest, tricep, and shoulder strength. Gradually move feet further from the wall to increase difficulty as strength and balance allow.',
 'Not maintaining a neutral spine (sagging hips or hiking them); standing too close to the wall (too easy) or not progressing further away as belly grows; not coordinating breath with the push.',
 'prenatal', array['Feet further from wall = harder: progress this way','Straight body: shoulder to heel alignment','Exhale on the push: coordinate breath with effort','Accommodate the belly: wall push-ups never compress the abdomen'],
 array['Incline push-up on a sturdy surface','Incline push-up on a Smith machine bar (adjustable height)','Seated chest press with resistance band (later pregnancy)'],
 array['Closest foot position to the wall','Seated chest press with light band','Standing chest fly with band'],
 array['prenatal','all_trimesters','push_up','chest','safe_pregnancy','wall'], array['wrist_injury','diastasis_recti_severe'],
 'push', 'sagittal', false, 3, 15, null, 60, true),

('Prenatal Seated Row with Band',
 'back', array['biceps','rear_deltoid'], array['back','biceps'],
 'strength', 'strength', array['resistance_band'], 'beginner', false,
 'Sit on the floor or a sturdy chair. Loop a resistance band around the feet (floor) or anchor at chest height (chair). Sit tall with a neutral spine. Row the band toward the lower ribs, driving the elbows back and squeezing the shoulder blades. Slowly return. Maintaining back strength during pregnancy counters the anterior pelvic tilt and increased thoracic kyphosis (rounded upper back) caused by breast enlargement and postural changes. This exercise is essential for posture and the prevention of upper back pain.',
 'Rounding the upper back during the row; pulling the arms instead of retracting the shoulder blades; using too much tension (the band pulls the torso forward, forcing a compensatory lean-back); holding the breath.',
 'prenatal', array['Sit tall: neutral spine throughout — this is the primary cue','Blades together: feel the scapular retraction','Light to moderate band: should feel challenging by rep 15','This counters pregnancy posture: rounded shoulders and kyphosis are corrected by this'],
 array['Seated cable row at a cable machine','Resistance band row with added external rotation','Dumbbell row seated with back supported'],
 array['Light band row with minimal tension','Band pull-apart (scapular exercise only)','Thoracic spine extension stretch'],
 array['prenatal','all_trimesters','row','back_strength','posture','resistance_band'], array['preeclampsia'],
 'pull', 'sagittal', false, 3, 15, null, 60, true),

-- ─── THIRD TRIMESTER (WEEKS 27–40) ────────────────────────────────────────────
('Prenatal Supported Squat (Birth Position)',
 'quadriceps', array['glutes','pelvic_floor'], array['quadriceps','glutes'],
 'functional', 'other', array['bodyweight'], 'intermediate', false,
 'The supported deep squat is one of the most important positions for labour preparation. Method: hold onto a TRX strap, door frame, or partner for support. Lower into a deep squat with the spine vertical. Hold for 30-60 seconds with relaxed breathing. Specifically: relax the pelvic floor in this position (let it go — do not Kegel). This prepares the pelvic floor for the relaxation phase of pushing during labour. Also opens the pelvis by up to 30% in the squatting position. Practice daily in the third trimester.',
 'Kegeling during the deep squat (the opposite of what is needed — the pelvic floor must relax here); not using support and losing balance; holding the breath; trying to achieve a deep squat without adequate hip mobility (use support to hold the position).',
 'prenatal', array['Pelvic floor relaxes: this is the opposite of a Kegel — let go','Hold with support: TRX, a door frame, or a partner — safety is key','Breathe into the pelvis: imagery of the floor dropping gently','Labour preparation: this is the pushing position — practice it'],
 array['Unsupported deep squat (near term if mobility allows)','Deep squat with pelvic floor relaxation breathing','Malasana yoga squat for hip preparation'],
 array['Chair squat (sit to chair depth only)','Supported shallow squat','Prenatal hip flexor stretch standing'],
 array['prenatal','third_trimester','deep_squat','labour_prep','pelvic_floor','birth_position'], array['symphysis_pubis_dysfunction','placenta_previa','preterm_labour'],
 'push', 'sagittal', false, 3, null, 45, 60, true),

('Prenatal Side-Lying Relaxation & Stretching',
 'core', array['hip_flexors','glutes'], array['core'],
 'mobility', 'flexibility', array['bodyweight'], 'beginner', false,
 'Lie on the left side (preferred for vena cava blood flow) with a pillow between the knees and one supporting the belly if needed. Perform gentle stretches: (1) Top hip gentle knee draw to chest — hip flexor and glute stretch. (2) Ankle circles for circulation. (3) Deep breathing and pelvic floor relaxation. (4) Neck rolls gently. This is a rest-based practice for the third trimester when fatigue is high and full exercise is limited. Also serves as labour preparation through body awareness and relaxation skill building.',
 'Lying on the right side or back for extended periods in the third trimester (left side preferred — avoids vena cava compression); overdoing the stretches and causing ligament strain (pregnancy hormones loosen ligaments significantly).',
 'prenatal', array['Left side preferred: improves blood flow to the placenta','Pillow support: between the knees, under the belly for comfort','Gentle: ligaments are loose in pregnancy — do not overstretch','Relax: this is rest-based, not performance-based'],
 array['Prenatal yoga class (side-lying focused)','Guided prenatal relaxation and breathing practice','Full body prenatal stretching routine'],
 array['Chair-based stretching','Short standing stretches','Prenatal walking for lighter activity'],
 array['prenatal','third_trimester','side_lying','relaxation','stretching','rest'], array['placenta_previa'],
 'isometric', 'frontal', true, 1, null, 600, null, true),

('Prenatal Aqua Fitness',
 'cardiovascular', array['quadriceps','glutes','core'], array['cardiovascular','quadriceps'],
 'cardio', 'other', array['pool'], 'beginner', false,
 'Water exercise during pregnancy: the buoyancy of water reduces body weight by 50-90%, dramatically reducing joint stress. Activities: (1) Water walking — both forward and backward. (2) Aqua jogging with a pool belt. (3) Side steps with resistance. (4) Standing leg swings in water. (5) Arm circles and upper body exercises in standing position. (6) Gentle water aerobics movements. Benefits: reduced back pain, lower extremity swelling reduction (hydrostatic pressure), cardiovascular fitness maintenance, and reduced overheating risk. Safe throughout all trimesters in a clean pool.',
 'Entering/exiting pool without assistance (slippery surfaces are a fall risk); overheating in a hot spa or hot tub (avoid water above 35°C during pregnancy); water aerobics classes not designed for pregnancy (too high impact); spending too long in cold water.',
 'prenatal', array['Pool temperature: 28-32°C is ideal — warm but not hot','Slip-safe entry: use the stairs with the railing — no jumping in','Hydrate: you still sweat in the pool — drink water','Duration: 30-45 minutes is appropriate — not a full high-intensity session'],
 array['Aqua jogging at higher intensity','Prenatal specific aqua aerobics class','Swim laps (if experienced swimmer)'],
 array['Walking on land','Seated exercise at home','Chair-based exercise for very limited mobility'],
 array['prenatal','all_trimesters','aqua','water','low_impact','joint_relief','cardio'], array['open_wounds','bladder_infection'],
 'mixed', 'multi', false, 1, null, 2700, null, true),

-- ─── POSTNATAL RECOVERY (0–6 WEEKS) ──────────────────────────────────────────
('Postnatal Diaphragmatic Breathing (Day 1+)',
 'core', array[], array['core'],
 'rehab', 'other', array['bodyweight'], 'beginner', false,
 'The first postnatal exercise: diaphragmatic (360°) breathing. Lie on your back with knees bent (or side-lying). Place one hand on the chest, one on the belly. Inhale through the nose: the belly rises, the chest minimal movement. The ribs expand in all directions (front, sides, back). Exhale through the mouth or nose: belly falls naturally. This restores proper breathing mechanics disrupted by pregnancy, begins reconnecting the diaphragm and pelvic floor, and is the foundation of all postnatal core rehabilitation. Safe from day 1 post-vaginal delivery or C-section.',
 'Chest breathing (shoulders rising and chest lifting — incorrect; should be belly-led); forcing too much belly movement (gentle, natural movement is correct); rushing progression to exercises before mastering this foundation; not practicing (even though it is simple, daily practice builds the neuromuscular connection).',
 'postnatal', array['Belly rises on inhale: not the chest','Ribcage expands 360°: front, sides, back, and toward the floor','Gentle: this is not deep yoga breathing extremes — just natural and diaphragmatic','Day one: this is appropriate from the first day after delivery'],
 array['Diaphragmatic breathing with pelvic floor coordination','Seated diaphragmatic breathing (more functional)','Walking with diaphragmatic breathing awareness'],
 array['Breathing only in comfortable supine position','Relaxation breathing only','No exercise — rest and observation'],
 array['postnatal','early_postnatal','breathing','diaphragm','pelvic_floor','day_one','foundation'], array[],
 'isometric', 'sagittal', false, 3, 10, null, 30, true),

('Postnatal Heel Slide',
 'core', array['hip_flexors'], array['core'],
 'rehab', 'other', array['bodyweight'], 'beginner', false,
 'Lie on the back with both knees bent. Perform a gentle abdominal brace (NOT a crunch — just find the tension). Slowly slide one heel along the floor, extending that leg to near-straight, then slide it back. The back should not arch — the core maintains neutral spine. This is a low-demand core stabilisation exercise that reconnects the deep core muscles (transverse abdominis, multifidus, pelvic floor) without placing excessive intra-abdominal pressure on the healing tissues. Appropriate from week 1-2 postnatally.',
 'Allowing the lower back to arch as the leg extends (the exercise is too demanding — modify by reducing range); doing full crunches or sit-ups instead (too much intra-abdominal pressure too early); rushing through without maintaining the brace.',
 'postnatal', array['Brace does not = crunch: find tension without rounding','Back stays flat: if it arches, reduce the leg extension range','Breathe through: exhale as the leg slides out','Week 1-2 appropriate: this is an early exercise — save crunches for months later'],
 array['Single-leg lowering (more demanding)','Bent-knee fallout','Dead bug progression'],
 array['Supine pelvic floor activation only','Breathing exercises only (days 0-3)','Diaphragmatic breathing with gentle brace'],
 array['postnatal','early_postnatal','heel_slide','core_reconnection','week_1','safe'], array['C_section_wound_recent'],
 'isometric', 'sagittal', true, 2, 10, null, 60, true),

('Postnatal Supine Glute Bridge',
 'glutes', array['hamstrings','core','pelvic_floor'], array['glutes','hamstrings'],
 'strength', 'strength', array['bodyweight'], 'beginner', false,
 'Lie on the back with knees bent, feet flat. Breathe in. On the exhale, gently engage the pelvic floor and lift the hips off the floor. Squeeze the glutes. Hold 2-3 seconds at the top with continued breathing. Lower slowly. The glute bridge restores glute activation (often inhibited during late pregnancy due to prolonged sitting and postural changes), activates the pelvic floor in a weight-bearing context, and begins loading the posterior chain without excessive pressure on the healing abdominal tissues. Appropriate from 2-3 weeks postnatally (vaginal delivery) or 6 weeks (C-section).',
 'Arching the lower back at the top (thrust with glutes, not the lumbar spine); holding the breath at the top; pelvic floor strain (if any leaking or pressure during the exercise — stop and consult a pelvic floor physiotherapist); rushing the progression.',
 'postnatal', array['Glutes squeeze: feel the posterior chain activate','Breathe at the top: do not hold the breath','No lower back arch: just the hips rising — pelvis and spine stay aligned','Pelvic floor lifts: coordinate the lift with the exhalation'],
 array['Single-leg glute bridge','Banded glute bridge','Hip thrust (later postnatal progression)'],
 array['Supine heel slide (earlier stage)','Supine breathing and pelvic floor activation','Side-lying hip abduction'],
 array['postnatal','early_postnatal','glute_bridge','glute_activation','pelvic_floor','week_2'], array['C_section_wound_recent','diastasis_recti_severe'],
 'push', 'sagittal', false, 3, 12, null, 60, true),

-- ─── DIASTASIS RECTI REHABILITATION ──────────────────────────────────────────
('Diastasis Recti – Tension Test and Assessment',
 'core', array[], array['core'],
 'rehab', 'other', array['bodyweight'], 'beginner', false,
 'Diastasis recti (DR) is the separation of the rectus abdominis muscles along the linea alba. Self-check: lie on your back, knees bent. Place fingers horizontally on the midline (navel). Lift just the head and shoulders. Feel for a gap: less than 2 finger-widths wide with tension (the tissue feels firm when you press) = functional. More than 2 fingers wide or no tension felt = consult a pelvic floor physiotherapist. Important: the GAP is less important than the TENSION in the linea alba. Many exercises are appropriate even with a larger gap if tension is present. Avoid: traditional crunches, sit-ups, heavy lifting, planks, and exercises that cause doming or coning of the belly.',
 'Doing standard crunches or sit-ups with diastasis recti; ignoring the issue and pushing through traditional core training; over-restricting all exercise unnecessarily when tension is adequate; not seeking physiotherapy assessment.',
 'diastasis_recti', array['Gap vs tension: the gap is less important than the tension — assess both','Doming = stop: if the midline domes or cones during any exercise, that exercise is contraindicated','Physio referral: any uncertainty warrants a pelvic floor physiotherapy assessment','Appropriate exercise continues: DR does not mean no exercise — it means MODIFIED exercise'],
 array['Full pelvic floor physiotherapy assessment','DR rehabilitation program with physiotherapist','Return to running and high-impact assessment'],
 array['Basic postnatal breathing only','Gentle stretching','Rest and awareness phase'],
 array['postnatal','diastasis_recti','assessment','linea_alba','core_separation','rehabilitation'], array[],
 'isometric', 'sagittal', false, 1, null, 60, null, true),

('Diastasis Recti – Dead Bug Modification',
 'core', array['hip_flexors'], array['core'],
 'rehab', 'other', array['bodyweight'], 'intermediate', false,
 'Modified dead bug for DR: lie on the back, knees bent to 90°, arms to the ceiling. Inhale to prepare. On the exhale, gently draw in the abdomen (without doming), maintain the brace, and extend ONE leg to 45° as the SAME-side arm extends overhead. Inhale to return. Alternate sides. CHECK: does the midline dome or cone during the movement? If yes — too demanding, regress. This exercise trains the anti-rotation and anti-extension function of the deep core while maintaining appropriate tension on the linea alba. Only progress when there is no doming and good tension is maintained.',
 'Any doming or coning of the midline (immediately regress the exercise — this is the primary monitoring cue for DR); breath holding; full leg extension before mastering the 45° range; not monitoring the midline throughout.',
 'diastasis_recti', array['Watch the midline: any doming = regress immediately','Same-side arm and leg: contralateral is harder — save for later','45° first: full range later only if midline stays flat','Exhale on the movement: core braces with the exhalation'],
 array['Contralateral arm-leg extension','Dead bug with full range extension','Dead bug with resistance band around the feet'],
 array['Heel slide (earlier stage)','Breathing and pelvic floor activation','Supine glute bridge (posterior chain, less core demand)'],
 array['postnatal','diastasis_recti','dead_bug','modified','linea_alba','core_stability'], array['diastasis_recti_severe_no_tension'],
 'isometric', 'sagittal', false, 3, 8, null, 60, true),

('Diastasis Recti – Standing Core Progressions',
 'core', array['glutes','shoulder'], array['core','glutes'],
 'strength', 'strength', array['resistance_band'], 'intermediate', false,
 'Standing exercises are more functional and appropriate for DR than floor exercises in many cases. Gravity assists in managing intra-abdominal pressure. Standing progressions: (1) Standing resistance band pull-apart (scapular retraction + core brace); (2) Standing pallof press (anti-rotation core stability); (3) Standing single-arm cable or band press (anti-extension and rotation); (4) Single-leg standing with contralateral arm reach (balance and core challenge). For all: brace gently, breathe through, and monitor for any midline doming.',
 'Performing these exercises without mastering the breath-brace coordination first; using too much resistance (midline will dome under excess load); progressing too quickly from floor to standing before adequate tension is restored in the linea alba.',
 'diastasis_recti', array['Standing is often easier: gravity helps manage pressure','Pallof press is excellent: anti-rotation core is functional','Monitor midline: even standing — watch for doming','Progress from horizontal: earn each position through the progressions'],
 array['Loaded carries (suitcase carry for lateral stability)','Return to resistance training full body','Return to high-impact activities (assessed by physiotherapist)'],
 array['Dead bug modification on the floor','Supine glute bridge','Heel slide core reconnection'],
 array['postnatal','diastasis_recti','standing','functional','pallof_press','anti_rotation'], array['diastasis_recti_severe_no_tension'],
 'mixed', 'multi', false, 3, 12, null, 60, true),

-- ─── POSTNATAL RETURN TO TRAINING (6–12 WEEKS+) ──────────────────────────────
('Postnatal Return to Training – Walk to Run Program',
 'cardiovascular', array['quadriceps','glutes'], array['cardiovascular','quadriceps'],
 'running', 'other', array['bodyweight'], 'beginner', false,
 'Minimum 12 weeks postnatally before return to running (BJSM 2019 guidelines). Prerequisites: able to walk briskly for 30 minutes without pain; single-leg calf raise 20 reps each side; single-leg squat 10 reps each side; no pelvic floor symptoms (leaking, prolapse heaviness). Walk-to-run program: Week 1-2: 1-minute run / 1-minute walk × 10 intervals. Week 3-4: 2-minute run / 1-minute walk × 8. Week 5-6: 3-minute run / 1-minute walk × 6. Progress only when symptom-free. Stop if any leaking, prolapse symptoms, or pain occur.',
 'Returning to running before 12 weeks postnatally (high risk of pelvic floor injury); not assessing the prerequisites before beginning (single-leg strength, pelvic floor symptoms); ignoring symptoms during the run (any leaking or prolapse heaviness is a red flag to stop and reassess).',
 'postnatal', array['12 weeks minimum: this is evidence-based — not arbitrary','Test prerequisites first: single-leg strength and no pelvic floor symptoms','Walk-run intervals: gradual re-introduction of impact','Listen to your body: symptoms are stop signs — not inconveniences'],
 array['Return to 5K running','Return to interval running training','Return to team sports (requires additional assessment)'],
 array['Walking only (earlier stage)','Pool running with belt (no impact)','Cycling (low impact cardio)'],
 array['postnatal','return_to_running','walk_run','12_weeks','pelvic_floor','impact_grading'], array['pelvic_organ_prolapse_symptomatic','stress_incontinence_active'],
 'locomotion', 'sagittal', false, 1, null, 1800, null, true),

('Postnatal Strength Return – Bodyweight Squat Progression',
 'quadriceps', array['glutes','hamstrings','core'], array['quadriceps','glutes'],
 'strength', 'strength', array['bodyweight'], 'beginner', true,
 'Progressive return to squatting strength after childbirth. Phase 1 (weeks 6-8): Sit-to-stand from chair, 3×15. Phase 2 (weeks 8-12): Bodyweight squat with perfect mechanics, 3×20. Phase 3 (weeks 12+): Goblet squat with light weight, 3×15. Phase 4 (weeks 16+): Barbell back squat or front squat at reduced weight from pre-pregnancy, 3×10. Coordinate pelvic floor lift with exhalation on the ascent. Monitor: no leaking, no prolapse heaviness, no pelvic or hip pain. Progress only when symptom-free.',
 'Rushing phases (skipping from chair squat to barbell squat in 8 weeks — too fast); not monitoring pelvic floor symptoms during the squat (any leaking means regression is needed); using pre-pregnancy weights too early; ignoring doming of the midline during loaded squats.',
 'postnatal', array['Exhale up: coordinate pelvic floor lift with the ascent','Symptom monitoring: leaking or heaviness = regress immediately','Phases take weeks: do not rush — the phases are minimum timeframes','Start light: pre-pregnancy strength returns but takes months — be patient'],
 array['Loaded barbell squat return to pre-pregnancy levels','Bulgarian split squat for unilateral strength','Squat-based high-intensity training programs'],
 array['Sit-to-stand from chair only (earliest stage)','Supported squat with TRX','Wall squat isometric'],
 array['postnatal','return_to_training','squat','progressive','pelvic_floor','strength_return'], array['pelvic_organ_prolapse_symptomatic'],
 'push', 'sagittal', false, 3, 15, null, 60, true),

('Postnatal Feeding Posture & Upper Body Recovery',
 'back', array['shoulder','core'], array['back','shoulder'],
 'rehab', 'other', array['bodyweight','resistance_band'], 'beginner', false,
 'Breastfeeding and bottle-feeding create repetitive forward flexion posture: head forward, shoulders rounded, thoracic kyphosis increased. Counter-exercises: (1) Thoracic extension over a foam roller (place the roller perpendicular to the spine at the mid-back, arms crossed, allow the head to drop back in gentle extension) — 3×60 seconds each vertebral level. (2) Chin tuck × 20. (3) Band pull-apart × 20 for scapular retraction. (4) Doorway chest stretch hold 30 seconds × 3. This counters feeding posture and reduces the epidemic of postnatal neck and upper back pain.',
 'Using the foam roller at the lower back (not appropriate for most — use only in the thoracic region from T4-T10); rolling too aggressively; neglecting this corrective work entirely despite hours of feeding posture daily.',
 'postnatal', array['Feeding is the enemy of posture: counter it deliberately','Foam roller placement: mid-back only (T4-T10), not lower back','Daily practice: 5-10 minutes after each main feeding session','Chin tuck first: decompresses the cervical spine before extending'],
 array['Regular upper body posture correction program','Rowing exercises with resistance band or cable','Thoracic mobilisation yoga class'],
 array['Gentle chin tuck only (earliest stage)','Thoracic extension stretch against a wall','Sitting posture correction during feeding only'],
 array['postnatal','feeding_posture','upper_back','thoracic','corrective','neck_pain'], array['cervical_instability'],
 'mixed', 'sagittal', false, 3, null, 60, 30, true);

-- ─── POSTNATAL MENTAL WELLBEING & RESTORATIVE ─────────────────────────────────
insert into exercises (name, primary_muscle_group, secondary_muscle_groups, muscle_groups, category, movement_type, equipment, difficulty_level, is_compound, instructions, common_mistakes, subcategory, coaching_cues, progressions, regressions, tags, contraindications, force_type, plane_of_motion, is_unilateral, sets_default, reps_default, duration_seconds, rest_seconds, is_system) values

('Postnatal Yoga – Restorative Sequence',
 'core', array['hip_flexors','glutes'], array['core'],
 'yoga_pilates', 'flexibility', array['yoga_mat','yoga_blocks'], 'beginner', false,
 'A gentle restorative yoga practice for postnatal recovery. Sequence (20-30 minutes): (1) Child''s pose with wide knees to accommodate postpartum belly — 2 minutes. (2) Cat-cow for spinal mobilisation — 1 minute. (3) Supine knees-to-chest gentle rock — 1 minute. (4) Happy baby pose (supine, holding the feet, gentle hip opening) — 2 minutes. (5) Supported savasana (pillow under knees, supported throughout) — 5 minutes. This sequence reduces cortisol, promotes parasympathetic nervous system recovery, improves pelvic mobility, and supports mental wellbeing. Clear with provider before starting.',
 'Performing yoga styles that are too vigorous (hot yoga, power yoga, or vinyasa flow — not appropriate in the early postnatal period); poses that require strong core (plank variations, boat pose — avoid until core is rehabilitated); rushing through without relaxing into the poses.',
 'postnatal', array['Restorative only: this is NOT a yoga workout — it is rest with movement','Modify everything: pregnancy and postpartum bodies need prop support','Breathe deeply: the breath is the primary tool here','5 minutes savasana: rest is non-negotiable — do not skip it'],
 array['Gentle flow yoga class (8-12 weeks postnatal)','Prenatal/postnatal yoga studio class','Yoga Nidra for deep rest and recovery'],
 array['Guided relaxation lying down only','Breathing and mindfulness practice','Rest in bed or on a mat'],
 array['postnatal','yoga','restorative','mental_wellbeing','gentle','recovery'], array['pelvic_organ_prolapse_symptomatic'],
 'isometric', 'multi', false, 1, null, 1800, null, true),

('Pelvic Organ Prolapse – Safe Exercise Screen',
 'core', array['glutes'], array['core'],
 'rehab', 'other', array['bodyweight'], 'beginner', false,
 'Pelvic organ prolapse (POP) affects approximately 50% of women who have delivered vaginally. Symptoms: sensation of heaviness, dragging, or bulging in the vaginal area; difficulty emptying the bladder or bowel; discomfort during exercise or intercourse. Safe exercise principles with POP: (1) Avoid high-impact activities (running, jumping) until medically assessed. (2) Avoid heavy lifting and breath-holding exercises. (3) Use exhale-on-effort pelvic floor coordination for all exercises. (4) Prioritise Kegels and pelvic floor strengthening. (5) All exercise choices should be symptom-free — if symptoms worsen during exercise, stop and see a pelvic floor physiotherapist.',
 'Ignoring prolapse symptoms and continuing high-impact exercise; high-intensity training without pelvic floor assessment; using waist trainers or abdominal binders without physiotherapy guidance; not seeking medical review of symptoms.',
 'postnatal', array['Symptom-free exercise: if it causes heaviness or pressure — stop','Exhale on effort: every single exercise, every rep','Low impact initially: walking, swimming, cycling are appropriate first steps','Physiotherapy is the gold standard: POP management requires specialist guidance'],
 array['Pelvic floor physiotherapy guided program','Pessary fitting and management guidance','Surgical consultation if conservative management fails'],
 array['Rest and observation','Breathing exercises only','Supine pelvic floor activation'],
 array['postnatal','pelvic_organ_prolapse','safe_exercise','pelvic_floor','management'], array['pelvic_organ_prolapse_stage_3_4_unmanaged'],
 'isometric', 'sagittal', false, 1, null, null, null, true),

('Baby-Inclusive Workout – Pram Walk with Intervals',
 'cardiovascular', array['quadriceps','glutes'], array['cardiovascular','quadriceps'],
 'cardio', 'other', array['pram'], 'beginner', false,
 'The pram (stroller) walk with intervals is a gateway to fitness for new parents who cannot arrange childcare. Start with 20 minutes of brisk walking. Add 1-minute faster walk (conversational effort becomes slightly harder) every 5 minutes. Progress over weeks: add hills, increase duration, and eventually include light jogging intervals. Pram running requires: a running pram (stroller designed for running), the baby at minimum 6 months old, and running clearance from a pelvic floor assessment. The social aspect — joining a pram walking group — improves postnatal mental health significantly.',
 'Using a non-running pram for running intervals (safety risk — not all prams are designed for running); pram running with a baby under 6 months (lack of head/neck control); pushing the pram at arm-width from the body (creates a poor posture — keep the pram close and walk with good posture).',
 'postnatal', array['Running pram for jogging: not all prams are running prams — check the specs','6 months minimum for running prams: head control development','Good posture: upright, not hunched over the pram handle','Join a group: pram walking groups are excellent for postnatal mental health'],
 array['Pram running intervals (6+ months with appropriate pram)','Pram walking hike with hills','Baby-wearing walk (different exercise — weight carried closer to centre of gravity)'],
 array['Short 10-minute walks only','Very slow stroll with rest stops','Seated indoor exercise if outdoor not possible'],
 array['postnatal','baby_inclusive','pram_walk','cardio','mother','mental_health'], array['pelvic_organ_prolapse_symptomatic','return_to_running_not_cleared'],
 'locomotion', 'sagittal', false, 1, null, 1800, null, true),

('Baby-Inclusive – Supine Baby Leg Press',
 'quadriceps', array['glutes'], array['quadriceps','glutes'],
 'strength', 'strength', array['bodyweight'], 'beginner', false,
 'Fun postnatal exercise including the baby. Lie on your back with knees bent, feet lifted. Place the baby tummy-down on your shins (holding the baby securely with your hands). Extend the legs to push the baby upward — airplane! Lower slowly. This is a gentle leg press with light resistance (the baby). Benefits: gentle quadricep and core activation, bonding time, and the joy-factor encourages adherence to postnatal exercise. Appropriate from 8-12 weeks postnatally when core has some rehabilitation. ONLY with a baby who has adequate head control (minimum 4-6 months) and while maintaining full hands-on support.',
 'Using with a newborn without head control (minimum 4-6 months); doing this without hands continuously on the baby; extending the legs fully fast and dropping the baby suddenly; doing this exercise if the mother has diastasis recti without core rehabilitation.',
 'postnatal', array['Hands on baby always: never release','Head control required: minimum 4-6 months old','Slow and controlled: this is not a power movement','Bonding exercise: make it playful and fun — the adherence benefit is enormous'],
 array['Baby overhead press (with full head control, supported)','Baby squat (holding baby in a front-carry position)','Baby-wearing weighted exercises'],
 array['Bodyweight supine leg press (no baby — earlier stage)','Supine glute bridge','Heel slide'],
 array['postnatal','baby_inclusive','bonding','leg_press','fun','postnatal_exercise'], array['diastasis_recti_unrehabilitated','baby_under_4_months'],
 'push', 'sagittal', false, 3, 10, null, 60, true),

('Postnatal Pilates – Core Reconnection',
 'core', array['pelvic_floor','glutes'], array['core'],
 'yoga_pilates', 'other', array['yoga_mat'], 'beginner', false,
 'Clinical postnatal Pilates focuses on deep core reconnection rather than six-pack aesthetics. Key exercises: (1) Imprinting (finding neutral spine on the mat); (2) Breathing with pelvic floor coordination; (3) Leg slides (heel slide equivalent); (4) Bent-knee fallout (single-leg hip external rotation with core brace); (5) Single-leg table top (legs lifted to 90° one at a time with breath management); (6) Gentle bridge. All performed with breathing cues and pelvic floor activation. Appropriate from 6 weeks postnatal (vaginal) or 8-10 weeks (C-section) with clearance.',
 'Performing Pilates 100s, roll-ups, or double-leg stretches too early (these create high intra-abdominal pressure — contraindicated for DR and early postnatal recovery); going to a regular Pilates class not designed for postnatal women.',
 'postnatal', array['Postnatal specific: not a regular Pilates class — it is specialized','Deep before global: transverse abdominis and pelvic floor before rectus abdominis','No coning: watch the midline for any doming on every exercise','6 week minimum: sooner than 6 weeks is too early for most women'],
 array['Full postnatal Pilates program with instructor','Intermediate Pilates return-to-class','Reformer Pilates for postnatal (6+ months)'],
 array['Breathing and pelvic floor coordination only','Physiotherapy-guided core exercises','Rest and recovery (pre-6 weeks)'],
 array['postnatal','pilates','core_reconnection','clinical','pelvic_floor','diastasis'], array['C_section_wound_not_healed'],
 'isometric', 'sagittal', false, 3, 10, null, 45, true);
